#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
#
# audi_codes.py
#
# Copyright (C) Ben Van Mechelen 2008-2009 <me@benvm.be>
# 
# This file is part of Garmon 
# 
# Garmon is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, write to:
#   The Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor
#   Boston, MA  02110-1301, USA.


from gettext import gettext as _

DTC_CODES_MANUFACTURER = {
    "P1101": _("O2 Sensor Circ.,Bank1-Sensor1Voltage too Low/Air Leak"),
    "P1102": _("O2 Sensor Heating Circ.,Bank1-Sensor1 Short to B+"),
    "P1103": _("O2 Sensor Heating Circ.,Bank1-Sensor1 Output too Low"),
    "P1104": _("Bank1-Sensor2 Voltage too Low/Air Leak"),
    "P1105": _("O2 Sensor Heating Circ.,Bank1-Sensor2 Short to B+"),
    "P1106": _("O2 Sensor Circ.,Bank2-Sensor1 Voltage too Low/Air Leak"),
    "P1107": _("O2 Sensor Heating Circ.,Bank2-Sensor1 Short to B+"),
    "P1108": _("O2 Sensor Heating Circ.,Bank2-Sensor1 Output too Low"),
    "P1109": _("O2 Sensor Circ.,Bank2-Sensor2 Voltage too Low/Air Leak"),
    "P1110": _("O2 Sensor Heating Circ.,Bank2-Sensor2 Short to B+"),
    "P1111": _("O2 Control (Bank 1) System too lean"),
    "P1112": _("O2 Control (Bank 1) System too rich"),
    "P1113": _("Bank1-Sensor1 Internal Resistance too High"),
    "P1114": _("Bank1-Sensor2 Internal Resistant too High"),
    "P1115": _("O2 Sensor Heater Circ.,Bank1-Sensor1 Short to Ground"),
    "P1116": _("O2 Sensor Heater Circ.,Bank1-Sensor1 Open"),
    "P1117": _("O2 Sensor Heater Circ.,Bank1-Sensor2 Short to Ground"),
    "P1118": _("O2 Sensor Heater Circ.,Bank1-Sensor2 Open"),
    "P1119": _("O2 Sensor Heater Circ.,Bank2-Sensor1 Short to Ground"),
    "P1120": _("O2 Sensor Heater Circ.,Bank2-Sensor1 Open"),
    "P1121": _("O2 Sensor Heater Circ.,Bank2-Sensor2 Short to Ground"),
    "P1122": _("O2 Sensor Heater Circ.,Bank2-Sensor2 Open"),
    "P1123": _("Long Term Fuel Trim Add.Air.,Bank1 System too Rich"),
    "P1124": _("Long Term Fuel Trim Add.Air.,Bank1 System too Lean"),
    "P1125": _("Long Term Fuel Trim Add.Air.,Bank2 System too Rich"),
    "P1126": _("Long Term Fuel Trim Add.Air.,Bank2 System too Lean"),
    "P1127": _("Long Term Fuel Trim mult.,Bank1 System too Rich"),
    "P1128": _("Long Term Fuel Trim mult.,Bank1 System too Lean"),
    "P1129": _("Long Term Fuel Trim mult.,Bank2 System too Rich"),
    "P1130": _("Long Term Fuel Trim mult.,Bank2 System too Lean"),
    "P1131": _("Bank2-Sensor1 Internal Rsistance too High"),
    "P1132": _("O2 Sensor Heating Circ.,Bank1+2-Sensor1 Short to B+"),
    "P1133": _("O2 Sensor Heating Circ.,Bank1+2-Sensor1 Electrical Malfunction"),
    "P1134": _("O2 Sensor Heating Circ.,Bank1+2-Sensor2 Short to B+"),
    "P1135": _("O2 Sensor Heating Circ.,Bank1+2-Sensor2 Electrical Malfunction"),
    "P1136": _("Long Term Fuel Trim Add.Fuel,Bank1 System too Lean"),
    "P1137": _("Long Term Fuel Trim Add.Fuel,Bank1 System too Rich"),
    "P1138": _("Long Term Fuel Trim Add.Fuel,Bank2 System too Lean"),
    "P1139": _("Long Term Fuel Trim Add.Fuel,Bank2 System too Rich"),
    "P1140": _("Bank2-Sensor2 Internal Resistance too High"),
    "P1141": _("Load Calculation Cross Check Range/Performance"),
    "P1142": _("Load Calculation Cross Check Lower Limit Exceeded"),
    "P1143": _("Load Calculation Cross Check Upper Limit Exceeded"),
    "P1144": _("Mass or Volume Air Flow Circ Open/Short to Ground"),
    "P1145": _("Mass or Volume Air Flow Circ Short to B+"),
    "P1146": _("Mass or Volume Air Flow Circ Supply Malfunction"),
    "P1147": _("O2 Control (Bank 2) System too lean"),
    "P1148": _("O2 Control (Bank 2) System too rich"),
    "P1149": _("O2 Control (Bank 1) Out of range"),
    "P1150": _("O2 Control (Bank 2) Out of range"),
    "P1151": _("Bank1, Long Term Fuel Trim, Range 1 Leanness Lower Limit Exceeded"),
    "P1152": _("Bank1, Long Term Fuel Trim, Range 2 Leanness Lower Limit Exceeded"),
    "P1154": _("Manifold Switch Over Malfunction"),
    "P1155": _("Manifold Abs.Pressure Sensor Circ. Short to B+"),
    "P1156": _("Manifold Abs.Pressure Sensor Circ. Open/Short to Ground"),
    "P1157": _("Manifold Abs.Pressure Sensor Circ. Power Supply Malfunction"),
    "P1158": _("Manifold Abs.Pressure Sensor Circ. Range/Performance"),
    "P1160": _("Manifold Temp.Sensor Circ. Short to Ground"),
    "P1161": _("Manifold Temp.Sensor Circ. Open/Short to B+"),
    "P1162": _("Fuel Temp.Sensor Circ. Short to Ground"),
    "P1163": _("Fuel Temp.Sensor Circ. Open/Short to B+"),
    "P1164": _("Fuel Temperature Sensor Range/Performance/Incorrect Signal"),
    "P1165": _("Bank1, Long Term Fuel Trim, Range 1 Rich Limit Exceeded"),
    "P1166": _("Bank1, Long Term Fuel Trim, Range 2 Rich Limit Exceeded"),
    "P1171": _("Throttle Actuation Potentiometer Sign.2 Range/Performance"),
    "P1172": _("Throttle Actuation Potentiometer Sign.2 Signal too Low"),
    "P1173": _("Throttle Actuation Potentiometer Sign.2 Signal too High"),
    "P1174": _("Fuel Trim, Bank 1 Different injection times"),
    "P1176": _("O2 Correction Behind Catalyst,B1 Limit Attained"),
    "P1177": _("O2 Correction Behind Catalyst,B2 Limit Attained"),
    "P1178": _("Linear 02 Sensor / Pump Current Open Circuit"),
    "P1179": _("Linear 02 Sensor / Pump Current Short to ground"),
    "P1180": _("Linear 02 Sensor / Pump Current Short to B+"),
    "P1181": _("Linear 02 Sensor / Reference Voltage Open Circuit"),
    "P1182": _("Linear 02 Sensor / Reference Voltage Short to ground"),
    "P1183": _("Linear 02 Sensor / Reference Voltage Short to B+"),
    "P1184": _("Linear 02 Sensor / Common Ground Wire Open Circuit"),
    "P1185": _("Linear 02 Sensor / Common Ground Wire Short to ground"),
    "P1186": _("Linear 02 Sensor / Common Ground Wire Short to B+"),
    "P1187": _("Linear 02 Sensor / Compens. Resistor Open Circuit"),
    "P1188": _("Linear 02 Sensor / Compens. Resistor Short to ground"),
    "P1189": _("Linear 02 Sensor / Compens. Resistor Short to B+"),
    "P1190": _("Linear 02 Sensor / Reference Voltage Incorrect Signal"),
    "P1196": _("O2 Sensor Heater Circ.,Bank1-Sensor1 Electrical Malfunction"),
    "P1197": _("O2 Sensor Heater Circ.,Bank2-Sensor1 Electrical Malfunction"),
    "P1198": _("O2 Sensor Heater Circ.,Bank1-Sensor2 Electrical Malfunction"),
    "P1199": _("O2 Sensor Heater Circ.,Bank2-Sensor2 Electrical Malfunction"),
    "P1201": _("Cyl.1-Fuel Inj.Circ. Electrical Malfunction"),
    "P1202": _("Cyl.2-Fuel Inj.Circ. Electrical Malfunction"),
    "P1203": _("Cyl.3-Fuel Inj.Circ. Electrical Malfunction"),
    "P1204": _("Cyl.4-Fuel Inj.Circ. Electrical Malfunction"),
    "P1205": _("Cyl.5-Fuel Inj.Circ. Electrical Malfunction"),
    "P1206": _("Cyl.6-Fuel Inj.Circ. Electrical Malfunction"),
    "P1207": _("Cyl.7-Fuel Inj.Circ. Electrical Malfunction"),
    "P1208": _("Cyl.8-Fuel Inj.Circ. Electrical Malfunction"),
    "P1209": _("Intake valves for cylinder shut-off Short circuit to ground"),
    "P1210": _("Intake valves for cylinder shut-off Short to B+"),
    "P1211": _("Intake valves for cylinder shut-off Open circuit"),
    "P1213": _("Cyl.1-Fuel Inj.Circ. Short to B+"),
    "P1214": _("Cyl.2-Fuel Inj.Circ. Short to B+"),
    "P1215": _("Cyl.3-Fuel Inj.Circ. Short to B+"),
    "P1216": _("Cyl.4-Fuel Inj.Circ. Short to B+"),
    "P1217": _("Cyl.5-Fuel Inj.Circ. Short to B+"),
    "P1218": _("Cyl.6-Fuel Inj.Circ. Short to B+"),
    "P1219": _("Cyl.7-Fuel Inj.Circ. Short to B+"),
    "P1220": _("Cyl.8-Fuel Inj.Circ. Short to B+"),
    "P1221": _("Cylinder shut-off exhaust valves Short circuit to ground"),
    "P1222": _("Cylinder shut-off exhaust valves Short to B+"),
    "P1223": _("Cylinder shut-off exhaust valves Open circuit"),
    "P1225": _("Cyl.1-Fuel Inj.Circ. Short to Ground"),
    "P1226": _("Cyl.2-Fuel Inj.Circ. Short to Ground"),
    "P1227": _("Cyl.3-Fuel Inj.Circ. Short to Ground"),
    "P1228": _("Cyl.4-Fuel Inj.Circ. Short to Ground"),
    "P1229": _("Cyl.5-Fuel Inj.Circ. Short to Ground"),
    "P1230": _("Cyl.6-Fuel Inj.Circ. Short to Ground"),
    "P1231": _("Cyl.7-Fuel Inj.Circ. Short to Ground"),
    "P1232": _("Cyl.8-Fuel Inj.Circ. Short to Ground"),
    "P1237": _("Cyl.1-Fuel Inj.Circ. Open Circ."),
    "P1238": _("Cyl.2-Fuel Inj.Circ. Open Circ."),
    "P1239": _("Cyl.3-Fuel Inj.Circ. Open Circ."),
    "P1240": _("Cyl.4-Fuel Inj.Circ. Open Circ."),
    "P1241": _("Cyl.5-Fuel Inj.Circ. Open Circ."),
    "P1242": _("Cyl.6-Fuel Inj.Circ. Open Circ."),
    "P1243": _("Cyl.7-Fuel Inj.Circ. Open Circ."),
    "P1244": _("Cyl.8-Fuel Inj.Circ. Open Circ."),
    "P1245": _("Needle Lift Sensor Circ. Short to Ground"),
    "P1246": _("Needle Lift Sensor Circ. Range/Performance"),
    "P1247": _("Needle Lift Sensor Circ. Open/Short to B+"),
    "P1248": _("Injection Start Control Deviation"),
    "P1249": _("Fuel consumption signal Electrical Fault in Circuit"),
    "P1250": _("Fuel Level Too Low"),
    "P1251": _("Start of Injection Solenoid Circ Short to B+"),
    "P1252": _("Start of Injection Solenoid Circ Open/Short to Ground"),
    "P1253": _("Fuel consumption signal Short to ground"),
    "P1254": _("Fuel consumption signal Short to B+"),
    "P1255": _("Engine Coolant Temp.Circ Short to Ground"),
    "P1256": _("Engine Coolant Temp.Circ Open/Short to B+"),
    "P1257": _("Engine Coolant System Valve Open"),
    "P1258": _("Engine Coolant System Valve Short to B+"),
    "P1259": _("Engine Coolant System Valve Short to Ground"),
    "P1280": _("Fuel Inj.Air Contr.Valve Circ. Flow too Low"),
    "P1283": _("Fuel Inj.Air Contr.Valve Circ. Electrical Malfunction"),
    "P1284": _("Fuel Inj.Air Contr.Valve Circ. Open"),
    "P1285": _("Fuel Inj.Air Contr.Valve Circ. Short to Ground"),
    "P1286": _("Fuel Inj.Air Contr.Valve Circ. Short to B+"),
    "P1287": _("Turbocharger bypass valve open"),
    "P1288": _("Turbocharger bypass valve short to B+"),
    "P1289": _("Turbocharger bypass valve short to ground"),
    "P1296": _("Cooling system malfunction"),
    "P1297": _("Connection turbocharger - throttle valve pressure hose"),
    "P1300": _("Misfire detected Reason: Fuel level too low"),
    "P1319": _("Knock Sensor 1 Circ. Short to Ground"),
    "P1320": _("Knock Sensor 2 Circ. Short to Ground"),
    "P1321": _("Knock Sensor 3 Circ. Low Input"),
    "P1322": _("Knock Sensor 3 Circ. High Input"),
    "P1323": _("Knock Sensor 4 Circ. Low Input"),
    "P1324": _("Knock Sensor 4 Circ. High Input"),
    "P1325": _("Cyl.1-Knock Contr. Limit Attained"),
    "P1326": _("Cyl.2-Knock Contr. Limit Attained"),
    "P1327": _("Cyl.3-Knock Contr. Limit Attained"),
    "P1328": _("Cyl.4-Knock Contr. Limit Attained"),
    "P1329": _("Cyl.5-Knock Contr. Limit Attained"),
    "P1330": _("Cyl.6-Knock Contr. Limit Attained"),
    "P1331": _("Cyl.7-Knock Contr. Limit Attained"),
    "P1332": _("Cyl.8-Knock Contr. Limit Attained"),
    "P1335": _("Engine Torque Monitoring 2 Control Limint Exceeded"),
    "P1336": _("Engine Torque Monitoring Adaptation at limit"),
    "P1337": _("Camshaft Pos.Sensor,Bank1 Short to Ground"),
    "P1338": _("Camshaft Pos.Sensor,Bank1 Open Circ./Short to B+"),
    "P1339": _("Crankshaft Pos./Engine Speed Sensor Cross Connected"),
    "P1340": _("Crankshaft-/Camshaft Pos.Sens.Signals Out of Sequence"),
    "P1341": _("Ignition Coil Power Output Stage 1 Short to Ground"),
    "P1342": _("Ignition Coil Power Output Stage 1 Short to B+"),
    "P1343": _("Ignition Coil Power Output Stage 2 Short to Ground"),
    "P1344": _("Ignition Coil Power Output Stage 2 Short to B+"),
    "P1345": _("Ignition Coil Power Output Stage 3 Short to Ground"),
    "P1346": _("Ignition Coil Power Output Stage 3 Short to B+"),
    "P1347": _("Bank2,Crankshaft-/Camshaft os.Sens.Sign. Out of Sequence"),
    "P1348": _("Ignition Coil Power Output Stage 1 Open Circuit"),
    "P1349": _("Ignition Coil Power Output Stage 2 Open Circuit"),
    "P1350": _("Ignition Coil Power Output Stage 3 Open Circuit"),
    "P1354": _("Modulation Piston Displ.Sensor Circ. Malfunction"),
    "P1355": _("Cyl. 1, ignition circuit Open Circuit"),
    "P1356": _("Cyl. 1, ignition circuit Short to B+"),
    "P1357": _("Cyl. 1, ignition circuit Short to ground"),
    "P1358": _("Cyl. 2, ignition circuit Open Circuit"),
    "P1359": _("Cyl. 2, ignition circuit Short Circuit to B+"),
    "P1360": _("Cyl. 2, ignition circuit Short Circuit to Ground"),
    "P1361": _("Cyl. 3, ignition circuit Open Circuit"),
    "P1362": _("Cyl. 3, ignition circuit Short Circuit to B+"),
    "P1363": _("Cyl. 3, ignition circuit Short Circuit to ground"),
    "P1364": _("Cyl. 4 ignition circuit Open Circuit"),
    "P1365": _("Cyl. 4 ignition circuit Short circuit to B+"),
    "P1366": _("Cyl. 4 ignition circuit Short circuit to ground"),
    "P1367": _("Cyl. 5, ignition circuit Open Circuit"),
    "P1368": _("Cyl. 5, ignition circuit Short Circuit to B+"),
    "P1369": _("Cyl. 5, ignition circuit short to ground"),
    "P1370": _("Cyl. 6, ignition circuit Open Circuit"),
    "P1371": _("Cyl. 6, ignition circuit Short Circuit to B+"),
    "P1372": _("Cyl. 6, ignition circuit short to ground"),
    "P1373": _("Cyl. 7, ignition circuit Open Circuit"),
    "P1374": _("Cyl. 7, ignition circuit Short Circuit to B+"),
    "P1375": _("Cyl. 7, ignition circuit short to ground"),
    "P1376": _("Cyl. 8, ignition circuit Open Circuit"),
    "P1377": _("Cyl. 8, ignition circuit Short Circuit to B+"),
    "P1378": _("Cyl. 8, ignition circuit short to ground"),
    "P1386": _("Internal Control Module Knock Control Circ.Error"),
    "P1387": _("Internal Contr. Module altitude sensor error"),
    "P1388": _("Internal Contr. Module drive by wire error"),
    "P1391": _("Camshaft Pos.Sensor,Bank2 Short to Ground"),
    "P1392": _("Camshaft Pos.Sensor,Bank2 Open Circ./Short to B+"),
    "P1393": _("Ignition Coil Power Output Stage 1 Electrical Malfunction"),
    "P1394": _("Ignition Coil Power Output Stage 2 Electrical Malfunction"),
    "P1395": _("Ignition Coil Power Output Stage 3 Electrical Malfunction"),
    "P1396": _("Engine Speed Sensor Missing Tooth"),
    "P1397": _("Engine speed wheel Adaptation limit reached"),
    "P1398": _("Engine RPM signal, TD Short to ground"),
    "P1399": _("Engine RPM signal, TD Short Circuit to B+"),
    "P1400": _("EGR Valve Circ Electrical Malfunction"),
    "P1401": _("EGR Valve Circ Short to Ground"),
    "P1402": _("EGR Valve Circ Short to B+"),
    "P1403": _("EGR Flow Deviation"),
    "P1404": _("EGR Flow Basic Setting not carried out"),
    "P1406": _("EGR Temp.Sensor Range/Performance"),
    "P1407": _("EGR Temp.Sensor Signal too Low"),
    "P1408": _("EGR Temp.Sensor Signal too High"),
    "P1409": _("Tank Ventilation Valve Circ. Electrical Malfunction"),
    "P1410": _("Tank Ventilation Valve Circ. Short to B+"),
    "P1411": _("Sec.Air Inj.Sys.,Bank2 Flow too Flow"),
    "P1412": _("EGR Different.Pressure Sensor Signal too Low"),
    "P1413": _("EGR Different.Pressure Sensor Signal too High"),
    "P1414": _("Sec.Air Inj.Sys.,Bank2 Leak Detected"),
    "P1417": _("Fuel Level Sensor Circ Signal too Low"),
    "P1418": _("Fuel Level Sensor Circ Signal too High"),
    "P1420": _("Sec.Air Inj.Valve Circ Electrical Malfunction"),
    "P1421": _("Sec.Air Inj.Valve Circ Short to Ground"),
    "P1422": _("Sec.Air Inj.Sys.Contr.Valve Circ Short to B+"),
    "P1423": _("Sec.Air Inj.Sys.,Bank1 Flow too Low"),
    "P1424": _("Sec.Air Inj.Sys.,Bank1 Leak Detected"),
    "P1425": _("Tank Vent.Valve Short to Ground"),
    "P1426": _("Tank Vent.Valve Open"),
    "P1432": _("Sec.Air Inj.Valve Open"),
    "P1433": _("Sec.Air Inj.Sys.Pump Relay Circ. open"),
    "P1434": _("Sec.Air Inj.Sys.Pump Relay Circ. Short to B+"),
    "P1435": _("Sec.Air Inj.Sys.Pump Relay Circ. Short to ground"),
    "P1436": _("Sec.Air Inj.Sys.Pump Relay Circ. Electrical Malfunction"),
    "P1439": _("EGR Potentiometer Error in Basic Seting"),
    "P1440": _("EGR Valve Power Stage Open"),
    "P1441": _("EGR Valve Circ Open/Short to Ground"),
    "P1442": _("EGR Valve Position Sensor Signal too high"),
    "P1443": _("EGR Valve Position Sensor Signal too low"),
    "P1444": _("EGR Valve Position Sensor range/performance"),
    "P1445": _("Catalyst Temp.Sensor 2 Circ. Range/Performance"),
    "P1446": _("Catalyst Temp.Circ Short to Ground"),
    "P1447": _("Catalyst Temp.Circ Open/Short to B+"),
    "P1448": _("Catalyst Temp.Sensor 2 Circ. Short to Ground"),
    "P1449": _("Catalyst Temp.Sensor 2 Circ. Open/Short to B+"),
    "P1450": _("Sec.Air Inj.Sys.Circ Short to B+"),
    "P1451": _("Sec.Air Inj.Sys.Circ Short to Ground"),
    "P1452": _("Sec.Air Inj.Sys. Open Circ."),
    "P1453": _("Exhaust gas temperature sensor 1 open/short to B+"),
    "P1454": _("Exhaust gas temperature sensor short 1 to ground"),
    "P1455": _("Exhaust gas temperature sensor 1 range/performance"),
    "P1456": _("Exhaust gas temperature control bank 1 limit attained"),
    "P1457": _("Exhaust gas temperature sensor 2 open/short to B+"),
    "P1458": _("Exhaust gas temperature sensor 2 short to ground"),
    "P1459": _("Exhaust gas temperature sensor 2 range/performance"),
    "P1460": _("Exhaust gas temperature control bank 2 limit attained"),
    "P1461": _("Exhaust gas temperature control bank 1 Range/Performance"),
    "P1462": _("Exhaust gas temperature control bank 2 Range/Performance"),
    "P1465": _("Additive Pump Short Circuit to B+"),
    "P1466": _("Additive Pump Open/Short to Ground"),
    "P1467": _("EVAP Canister Purge Solenoid Valve Short Circuit to B+"),
    "P1468": _("EVAP Canister Purge Solenoid Valve Short Circuit to Ground"),
    "P1469": _("EVAP Canister Purge Solenoid Valve Open Circuit"),
    "P1470": _("EVAP Emission Contr.LDP Circ Electrical Malfunction"),
    "P1471": _("EVAP Emission Contr.LDP Circ Short to B+"),
    "P1472": _("EVAP Emission Contr.LDP Circ Short to Ground"),
    "P1473": _("EVAP Emission Contr.LDP Circ Open Circ."),
    "P1474": _("EVAP Canister Purge Solenoid Valve electrical malfunction"),
    "P1475": _("EVAP Emission Contr.LDP Circ Malfunction/Signal Circ.Open"),
    "P1476": _("EVAP Emission Contr.LDP Circ Malfunction/Insufficient Vacuum"),
    "P1477": _("EVAP Emission Contr.LDP Circ Malfunction"),
    "P1478": _("EVAP Emission Contr.LDP Circ Clamped Tube Detected"),
    "P1500": _("Fuel Pump Relay Circ. Electrical Malfunction"),
    "P1501": _("Fuel Pump Relay Circ. Short to Ground"),
    "P1502": _("Fuel Pump Relay Circ. Short to B+"),
    "P1503": _("Load signal from Alternator Term. DF Range/performance/Incorrect Signal"),
    "P1504": _("Intake Air Sys.Bypass Leak Detected"),
    "P1505": _("Closed Throttle Pos. Does Not Close/Open Circ"),
    "P1506": _("Closed Throttle Pos.Switch Does Not Open/Short to Ground"),
    "P1507": _("Idle Sys.Learned Value Lower Limit Attained"),
    "P1508": _("Idle Sys.Learned Value Upper Limit Attained"),
    "P1509": _("Idle Air Control Circ. Electrical Malfunction"),
    "P1510": _("Idle Air Control Circ. Short to B+"),
    "P1511": _("Intake Manifold Changeover Valve circuit electrical malfunction"),
    "P1512": _("Intake Manifold Changeover Valve circuit Short to B+"),
    "P1513": _("Intake Manifold Changeover Valve2 circuit Short to B+"),
    "P1514": _("Intake Manifold Changeover Valve2 circuit Short to ground"),
    "P1515": _("Intake Manifold Changeover Valve circuit Short to Ground"),
    "P1516": _("Intake Manifold Changeover Valve circuit Open"),
    "P1517": _("Main Relay Circ. Electrical Malfunction"),
    "P1518": _("Main Relay Circ. Short to B+"),
    "P1519": _("Intake Camshaft Contr.,Bank1 Malfunction"),
    "P1520": _("Intake Manifold Changeover Valve2 circuit Open"),
    "P1521": _("Intake Manifold Changeover Valve2 circuit electrical malfunction"),
    "P1522": _("Intake Camshaft Contr.,Bank2 Malfunction"),
    "P1523": _("Crash Signal from Airbag Control Unit range/performance"),
    "P1525": _("Intake Camshaft Contr.Circ.,Bank1 Electrical Malfunction"),
    "P1526": _("Intake Camshaft Contr.Circ.,Bank1 Short to B+"),
    "P1527": _("Intake Camshaft Contr.Circ.,Bank1 Short to Ground"),
    "P1528": _("Intake Camshaft Contr.Circ.,Bank1 Open"),
    "P1529": _("Camshaft Control Circuit Short to B+"),
    "P1530": _("Camshaft Control Circuit Short to ground"),
    "P1531": _("Camshaft Control Circuit open"),
    "P1533": _("Intake Camshaft Contr.Circ.,Bank2 Electrical Malfunction"),
    "P1534": _("Intake Camshaft Contr.Circ.,Bank2 Short to B+"),
    "P1535": _("Intake Camshaft Contr.Circ.,Bank2 Short to Ground"),
    "P1536": _("Intake Camshaft Contr.Circ.,Bank2 Open"),
    "P1537": _("Engine Shutoff Solenoid Malfunction"),
    "P1538": _("Engine Shutoff Solenoid Open/Short to Ground"),
    "P1539": _("Clutch Vacuum Vent Valve Switch Incorrect signal"),
    "P1540": _("Vehicle Speed Sensor High Input"),
    "P1541": _("Fuel Pump Relay Circ Open"),
    "P1542": _("Throttle Actuation Potentiometer Range/Performance"),
    "P1543": _("Throttle Actuation Potentiometer Signal too Low"),
    "P1544": _("Throttle Actuation Potentiometer Signal too High"),
    "P1545": _("Throttle Pos.Contr Malfunction"),
    "P1546": _("Boost Pressure Contr.Valve Short to B+"),
    "P1547": _("Boost Pressure Contr.Valve Short to Ground"),
    "P1548": _("Boost Pressure Contr.Valve Open"),
    "P1549": _("Boost Pressure Contr.Valve Short to Ground"),
    "P1550": _("Charge Pressure Deviation"),
    "P1551": _("Barometric Pressure Sensor Circ. Short to B+"),
    "P1552": _("Barometric Pressure Sensor Circ. Open/Short to Ground"),
    "P1553": _("Barometric/manifold pressure signal ratio out of range"),
    "P1554": _("Idle Speed Contr.Throttle Pos. Basic Setting Conditions not met"),
    "P1555": _("Charge Pressure Upper Limit exceeded"),
    "P1556": _("Charge Pressure Contr. Negative Deviation"),
    "P1557": _("Charge Pressure Contr. Positive Deviation"),
    "P1558": _("Throttle Actuator Electrical Malfunction"),
    "P1559": _("Idle Speed Contr.Throttle Pos. Adaptation Malfunction"),
    "P1560": _("Maximum Engine Speed Exceeded"),
    "P1561": _("Quantity Adjuster Deviation"),
    "P1562": _("Quantity Adjuster Upper Limit Attained"),
    "P1563": _("Quantity Adjuster Lower Limit Attained"),
    "P1564": _("Idle Speed Contr.Throttle Pos. Low Voltage During Adaptation"),
    "P1565": _("Idle Speed Control Throttle Position lower limit not attained"),
    "P1566": _("Load signal from A/C compressor range/performance"),
    "P1567": _("Load signal from A/C compressor no signal"),
    "P1568": _("Idle Speed Contr.Throttle Pos. mechanical Malfunction"),
    "P1569": _("Cruise control switch Incorrect signal"),
    "P1570": _("Contr.Module Locked"),
    "P1571": _("Left Eng. Mount Solenoid Valve Short to B+"),
    "P1572": _("Left Eng. Mount Solenoid Valve Short to ground"),
    "P1573": _("Left Eng. Mount Solenoid Valve Open circuit"),
    "P1574": _("Left Eng. Mount Solenoid Valve Electrical fault in circuit"),
    "P1575": _("Right Eng. Mount Solenoid Valve Short to B+"),
    "P1576": _("Right Eng. Mount Solenoid Valve Short to ground"),
    "P1577": _("Right Eng. Mount Solenoid Valve Open circuit"),
    "P1578": _("Right Eng. Mount Solenoid Valve Electrical fault in circuit"),
    "P1579": _("Idle Speed Contr.Throttle Pos. Adaptation not started"),
    "P1580": _("Throttle Actuator B1 Malfunction"),
    "P1581": _("Idle Speed Contr.Throttle Pos. Basic Setting Not Carried Out"),
    "P1582": _("Idle Adaptation at Limit"),
    "P1583": _("Transmission mount valves Short to B+"),
    "P1584": _("Transmission mount valves Short to ground"),
    "P1585": _("Transmission mount valves Open circuit"),
    "P1586": _("Engine mount solenoid valves Short to B+"),
    "P1587": _("Engine mount solenoid valves Short to ground"),
    "P1588": _("Engine mount solenoid valves Open circuit"),
    "P1600": _("Power Supply (B+) Terminal 15 Low Voltage"),
    "P1602": _("Power Supply (B+) Terminal 30 Low Voltage"),
    "P1603": _("Internal Control Module Malfunction"),
    "P1604": _("Internal Control Module Driver Error"),
    "P1605": _("Rough Road/Acceleration Sensor Electrical Malfunction"),
    "P1606": _("Rough Road Spec Engine Torque ABS-ECU Electrical Malfunction"),
    "P1607": _("Vehicle speed signal Error message from instrument cluster"),
    "P1608": _("Steering angle signal Error message from steering angle sensor"),
    "P1609": _("Crash shut-down activated"),
    "P1611": _("MIL Call-up Circ./Transm.Contr.Module Short to Ground"),
    "P1612": _("Electronic Control Module Incorrect Coding"),
    "P1613": _("MIL Call-up Circ Open/Short to B+"),
    "P1614": _("MIL Call-up Circ./Transm.Contr.Module Range/Performance"),
    "P1615": _("Engine Oil Temperature Sensor Circuit range/performance"),
    "P1616": _("Glow Plug/Heater Indicator Circ. Short to B+"),
    "P1617": _("Glow Plug/Heater Indicator Circ. Open/Short to Ground"),
    "P1618": _("Glow Plug/Heater Relay Circ. Short to B+"),
    "P1619": _("Glow Plug/Heater Relay Circ. Open/Short to Ground"),
    "P1620": _("Engine coolant temperature signal open/short to B+"),
    "P1621": _("Engine coolant temperature signal short to ground"),
    "P1622": _("Engine coolant temperature signal range/performance"),
    "P1623": _("Data Bus Powertrain No Communication"),
    "P1624": _("MIL Request Sign.active"),
    "P1625": _("Data-Bus Powertrain Unplausible Message from Transm.Contr."),
    "P1626": _("Data-Bus Powertrain Missing Message from Transm.Contr."),
    "P1627": _("Data-Bus Powertrain missing message from fuel injection pump"),
    "P1628": _("Data-Bus Powertrain missing message from steering sensor"),
    "P1629": _("Data-Bus Powertrain missing message from distance control"),
    "P1630": _("Accelera.Pedal Pos.Sensor 1 Signal too Low"),
    "P1631": _("Accelera.Pedal Pos.Sensor 1 Signal too High"),
    "P1632": _("Accelera.Pedal Pos.Sensor 1 Power Supply Malfunction"),
    "P1633": _("Accelera.Pedal Pos.Sensor 2 Signal too Low"),
    "P1634": _("Accelera.Pedal Pos.Sensor 2 Signal too High"),
    "P1635": _("Data Bus Powertrain missing message f.air condition control"),
    "P1636": _("Data Bus Powertrain missing message from Airbag control"),
    "P1637": _("Data Bus Powertrain missing message f.central electr.control"),
    "P1638": _("Data Bus Powertrain missing message from clutch control"),
    "P1639": _("Accelera.Pedal Pos.Sensor 1+2 Range/Performance"),
    "P1640": _("Internal Contr.Module (EEPROM) Error"),
    "P1641": _("Please check DTC Memory of Air Condition ECU"),
    "P1642": _("Please check DTC Memory of Airbag ECU"),
    "P1643": _("Please check DTC Memory of central electric ECU"),
    "P1644": _("Please check DTC Memory of clutch ECU"),
    "P1645": _("Data Bus Powertrain missing message f.all wheel drive contr."),
    "P1646": _("Please Check DTC Memory of all wheel drive ECU"),
    "P1647": _("Please check coding of ECUs in Data Bus Powertrain"),
    "P1648": _("Data Bus Powertrain Malfunction"),
    "P1649": _("Data Bus Powertrain Missing message from ABS Control Module"),
    "P1650": _("Data Bus Powertrain Missing message fr.instrument panel ECU"),
    "P1651": _("Data Bus Powertrain missing messages"),
    "P1652": _("Please check DTC Memory of transmission ECU"),
    "P1653": _("Please check DTC Memory of ABS Control Module"),
    "P1654": _("Please check DTC Memory of control panel ECU"),
    "P1655": _("Please check DTC Memory of ADR Control Module"),
    "P1656": _("A/C clutch relay circuit short to ground"),
    "P1657": _("A/C clutch relay circuit short to B+"),
    "P1658": _("Data Bus Powertrain Incorrect signal from ADR Control Module"),
    "P1676": _("Drive by Wire-MIL Circ. Electrical Malfunction"),
    "P1677": _("Drive by Wire-MIL Circ. Short to B+"),
    "P1678": _("Drive by Wire-MIL Circ. Short to Ground"),
    "P1679": _("Drive by Wire-MIL Circ. Open"),
    "P1681": _("Contr.Unit Programming, Programming not Finished"),
    "P1684": _("Contr.Unit Programming Communication Error"),
    "P1686": _("Contr.Unit Error Programming Error"),
    "P1690": _("Malfunction Indication Light Malfunction"),
    "P1691": _("Malfunction Indication Light Open"),
    "P1692": _("Malfunction Indication Light Short to Ground"),
    "P1693": _("Malfunction Indication Light Short to B+"),
    "P1694": _("Malfunction Indication Light Open/Short to Ground"),
    "P1704": _("Kick Down Switch Malfunction"),
    "P1705": _("Gear/Ratio Monitoring Adaptation limit reached"),
    "P1711": _("Wheel Speed Signal 1 Range/Performance"),
    "P1716": _("Wheel Speed Signal 2 Range/Performance"),
    "P1721": _("Wheel Speed Signal 3 Range/Performance"),
    "P1723": _("Starter Interlock Circ. Open"),
    "P1724": _("Starter Interlock Circ. Short to Ground"),
    "P1726": _("Wheel Speed Signal 4 Range/Performance"),
    "P1728": _("Different Wheel Speed Signals Range/Performance"),
    "P1729": _("Starter Interlock Circ. Short to B+"),
    "P1733": _("Tiptronic Switch Down Circ. Short to Ground"),
    "P1739": _("Tiptronic Switch up Circ. Short to Ground"),
    "P1740": _("Clutch temperature control"),
    "P1741": _("Clutch pressure adaptation at limit"),
    "P1742": _("Clutch torque adaptation at limit"),
    "P1743": _("Clutch slip control signal too high"),
    "P1744": _("Tiptronic Switch Recognition Circ. Short to Ground"),
    "P1745": _("Transm.Contr.Unit Relay Short to B+"),
    "P1746": _("Transm.Contr.Unit Relay Malfunction"),
    "P1747": _("Transm.Contr.Unit Relay Open/Short to Ground"),
    "P1748": _("Transm.Contr.Unit Self-Check"),
    "P1749": _("Transm.Contr.Unit Incorrect Coded"),
    "P1750": _("Power Supply Voltage Low Voltage"),
    "P1751": _("Power Supply Voltage High Voltage"),
    "P1752": _("Power Supply Malfunction"),
    "P1760": _("Shift Lock Malfunction"),
    "P1761": _("Shift Lock Short to Ground"),
    "P1762": _("Shift Lock Short to B+"),
    "P1763": _("Shift Lock Open"),
    "P1764": _("Transmission temperature control"),
    "P1765": _("Hydraulic Pressure Sensor 2 adaptation at limit"),
    "P1766": _("Throttle Angle Signal Stuck Off"),
    "P1767": _("Throttle Angle Signal Stuck On"),
    "P1768": _("Hydraulic Pressure Sensor 2 Too High"),
    "P1769": _("Hydraulic Pressure Sensor 2 Too Low"),
    "P1770": _("Load Signal Range/Performance"),
    "P1771": _("Load Signal Stuck Off"),
    "P1772": _("Load Signal Stuck On"),
    "P1773": _("Hydraulic Pressure Sensor 1 Too High"),
    "P1774": _("Hydraulic Pressure Sensor 1 Too Low"),
    "P1775": _("Hydraulic Pressure Sensor 1 adaptation at limit"),
    "P1776": _("Hydraulic Pressure Sensor 1 range/performance"),
    "P1777": _("Hydraulic Pressure Sensor 2 range/performance"),
    "P1778": _("Solenoid EV7 Electrical Malfunction"),
    "P1781": _("Engine Torque Reduction Open/Short to Ground"),
    "P1782": _("Engine Torque Reduction Short to B+"),
    "P1784": _("Shift up/down Wire Open/Short to Ground"),
    "P1785": _("Shift up/down Wire Short to B+"),
    "P1786": _("Reversing Light Circ. Open"),
    "P1787": _("Reversing Light Circ. Short to Ground"),
    "P1788": _("Reversing Light Circ. Short to B+"),
    "P1789": _("Idle Speed Intervention Circ. Error Message from Engine Contr."),
    "P1790": _("Transmission Range Display Circ. Open"),
    "P1791": _("Transmission Range Display Circ. Short to Ground"),
    "P1792": _("Transmission Range Display Circ. Short to B+"),
    "P1793": _("Output Speed Sensor 2 Circ. No Signal"),
    "P1795": _("Vehicle Speed Signal Circ. Open"),
    "P1796": _("Vehicle Speed Signal Circ. Short to Ground"),
    "P1797": _("Vehicle Speed Signal Circ. Short to B+"),
    "P1798": _("Output Speed Sensor 2 Circ. Range/Performance"),
    "P1799": _("Output Speed Sensor 2 Circ. Rpm too High"),
    "P1813": _("Pressure Contr.Solenoid 1 Electrical"),
    "P1814": _("Pressure Contr.Solenoid 1 Open/Short to Ground"),
    "P1815": _("Pressure Contr.Solenoid 1 Short to B+"),
    "P1818": _("Pressure Contr.Solenoid 2 Electrical"),
    "P1819": _("Pressure Contr.Solenoid 2 Open/Short to Ground"),
    "P1820": _("Pressure Contr.Solenoid 2 Short to B+"),
    "P1823": _("Pressure Contr.Solenoid 3 Electrical"),
    "P1824": _("Pressure Contr.Solenoid 3 Open/Short to Ground"),
    "P1825": _("Pressure Contr.Solenoid 3 Short to B+"),
    "P1828": _("Pressure Contr.Solenoid 4 Electrical"),
    "P1829": _("Pressure Contr.Solenoid 4 Open/Short to Ground"),
    "P1830": _("Pressure Contr.Solenoid 4 Short to B+"),
    "P1834": _("Pressure Contr.Solenoid 5 Open/Short to Ground"),
    "P1835": _("Pressure Contr.Solenoid 5 Short to B+"),
    "P1841": _("Engine/Transmission Control Modules Versions do not match"),
    "P1842": _("Please check DTC Memory of instrument panel ECU"),
    "P1843": _("Please check DTC Memory of ADR Control Module"),
    "P1844": _("Please check DTC Memory of central electric control ECU"),
    "P1847": _("Please check DTC Memory of brake system ECU"),
    "P1848": _("Please check DTC Memory of engine ECU"),
    "P1849": _("Please check DTC Memory of transmission ECU"),
    "P1850": _("Data-Bus Powertrain Missing Message from Engine Contr."),
    "P1851": _("Data-Bus Powertrain Missing Message from Brake Contr."),
    "P1852": _("Data-Bus Powertrain Unplausible Message from Engine Contr."),
    "P1853": _("Data-Bus Powertrain Unplausible Message from Brake Contr."),
    "P1854": _("Data-Bus Powertrain Hardware Defective"),
    "P1855": _("Data-Bus Powertrain Software version Contr."),
    "P1856": _("Throttle/Pedal Pos.Sensor A Circ. Error Message from Engine Contr."),
    "P1857": _("Load Signal Error Message from Engine Contr."),
    "P1858": _("Engine Speed Input Circ. Error Message from Engine Contr."),
    "P1859": _("Brake Switch Circ. Error Message from Engine Contr."),
    "P1860": _("Kick Down Switch Error Message from Engine Contr."),
    "P1861": _("Throttle Position (TP) sensor Error Message from ECM"),
    "P1862": _("Data Bus Powertrain Missing message from instr. panel ECU"),
    "P1863": _("Data Bus Powertrain Missing Message from St. Angle Sensor"),
    "P1864": _("Data Bus Powertrain Missing message from ADR control module"),
    "P1865": _("Data Bus Powertrain Missing message from central electronics"),
    "P1866": _("Data Bus Powertrain Missing messages"),
}
