#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
#
# ford_codes.py
#
# Copyright (C) Ben Van Mechelen 2008-2009 <me@benvm.be>
# 
# This file is part of Garmon 
# 
# Garmon is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, write to:
#   The Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor
#   Boston, MA  02110-1301, USA.


from gettext import gettext as _

DTC_CODES_MANUFACTURER = {
    "P1000": _("OBD-II Monitor Testing Incomplete"),
    "P1001": _("KOER Test Cannot Be Completed"),
    "P1039": _("Vehicle Speed Signal Missing or Improper"),
    "P1051": _("Brake Switch Signal Missing or Improper"),
    "P1100": _("Mass Air Flow Sensor Intermittent"),
    "P1101": _("Mass Air Flow Sensor out of Self-Test Range"),
    "P1112": _("Intake Air Temperature Sensor Intermittent"),
    "P1116": _("Engine Coolant Temperature Sensor is out of Self-Test Range"),
    "P1117": _("Engine Coolant Temperature Sensor Intermittent"),
    "P1120": _("Throttle Position Sensor out of range"),
    "P1121": _("Throttle Position Sensor Inconsistent with Mass Air Flow Sensor"),
    "P1124": _("Throttle Position Sensor out of Self-Test Range"),
    "P1125": _("Throttle Position Sensor Intermittent"),
    "P1127": _("Heated Oxygen Sensor Heater not on During KOER Test"),
    "P1128": _("Heated Oxygen Sensor Signals reversed"),
    "P1129": _("Heated Oxygen Sensor Signals reversed"),
    "P1130": _("Lack of Upstream Heated Oxygen Sensor Switch - Adaptive Fuel Limit - Bank No. 1"),
    "P1131": _("Lack of Upstream Heated Oxygen Sensor Switch - Sensor Indicates Lean - Bank No. 1"),
    "P1132": _("Lack of Upstream Heated Oxygen Sensor Switch - Sensor Indicates Rich - Bank No. 1"),
    "P1135": _("Ignition Switch Signal Missing or Improper"),
    "P1137": _("Lack of Downstream Heated Oxygen Sensor Switch - Sensor Indicates Lean - Bank No. 1"),
    "P1138": _("Lack of Downstream Heated Oxygen Sensor Switch - Sensor Indicates Rich - Bank No. 1"),
    "P1150": _("Lack of Upstream Heated Oxygen Sensor Switch - Adaptive Fuel Limit - Bank No. 2"),
    "P1151": _("Lack of Upstream Heated Oxygen Sensor Switch - Sensor Indicates Lean - Bank No. 2"),
    "P1152": _("Lack of Upstream Heated Oxygen Sensor Switch - Sensor Indicates Rich - Bank No. 2"),
    "P1157": _("Lack of Downstream Heated Oxygen Sensor Switch - Sensor Indicates Lean - Bank No. 2"),
    "P1158": _("Lack of Downstream Heated Oxygen Sensor Switch - Sensor Indicates Rich - Bank No. 2"),
    "P1220": _("Series Throttle Control fault"),
    "P1224": _("Throttle Position Sensor B out of Self-Test Range"),
    "P1230": _("Open Power to Fuel Pump circuit"),
    "P1231": _("High Speed Fuel Pump Relay activated"),
    "P1232": _("Low Speed Fuel Pump Primary circuit failure"),
    "P1233": _("Fuel Pump Driver Module off-line"),
    "P1234": _("Fuel Pump Driver Module off-line"),
    "P1235": _("Fuel Pump Control out of range"),
    "P1236": _("Fuel Pump Control out of range"),
    "P1237": _("Fuel Pump Secondary circuit fault"),
    "P1238": _("Fuel Pump Secondary circuit fault"),
    "P1250": _("Lack of Power to FPRC Solenoid"),
    "P1260": _("Theft Detected - Engine Disabled"),
    "P1270": _("Engine RPM or Vehicle Speed Limiter Reached"),
    "P1288": _("Cylinder Head Temperature Sensor out of Self-Test Range"),
    "P1289": _("Cylinder Head Temperature Sensor Signal Greater Than Self-Test Range"),
    "P1290": _("Cylinder Head Temperature Sensor Signal Less Than Self-Test Range"),
    "P1299": _("Cylinder Head Temperature Sensor Detected Engine Overheating Condition"),
    "P1309": _("Misfire Detection Monitor not enabled"),
    "P1351": _("Ignition Diagnostic Monitor circuit Input fault"),
    "P1352": _("Ignition Coil A - Primary circuit fault"),
    "P1353": _("Ignition Coil B - Primary circuit fault"),
    "P1354": _("Ignition Coil C - Primary circuit fault"),
    "P1355": _("Ignition Coil D - Primary circuit fault"),
    "P1356": _("Loss of Ignition Diagnostic Module Input to PCM"),
    "P1358": _("Ignition Diagnostic Monitor Signal out of Self-Test Range"),
    "P1359": _("Spark Output circuit fault"),
    "P1364": _("Ignition Coil Primary circuit fault"),
    "P1380": _("VCT Solenoid Valve circuit Short or Open"),
    "P1381": _("Cam Timing Advance is excessive"),
    "P1383": _("Cam Timing Advance is excessive"),
    "P1390": _("Octane Adjust out of Self-Test Range"),
    "P1400": _("Differential Pressure Feedback Electronic Sensor circuit Low Voltage"),
    "P1401": _("Differential Pressure Feedback Electronic Sensor circuit High Voltage"),
    "P1403": _("Differential Pressure Feedback Electronic Sensor Hoses Reversed"),
    "P1405": _("Differential Pressure Feedback Electronic Sensor circuit Upstream Hose"),
    "P1406": _("Differential Pressure Feedback Electronic Sensor circuit Downstream Hose"),
    "P1407": _("EGR No Flow Detected"),
    "P1408": _("EGR Flow out of Self-Test Range"),
    "P1409": _("EGR Vacuum Regulator circuit malfunction"),
    "P1410": _("EGR Barometric Pressure Sensor VREF Voltage"),
    "P1411": _("Secondary Air is not being diverted"),
    "P1413": _("Secondary Air Injection System Monitor circuit Low Voltage"),
    "P1414": _("Secondary Air Injection System Monitor circuit High Voltage"),
    "P1442": _("Secondary Air Injection System Monitor circuit High Voltage"),
    "P1443": _("Evaporative Emission Control System - Vacuum System - Purge Control Solenoid or Purge Control Valve fault"),
    "P1444": _("Purge Flow Sensor circuit Input Low"),
    "P1445": _("Purge Flow Sensor circuit Input High"),
    "P1450": _("Inability of Evaporative Emission Control System to Bleed Fuel Tank"),
    "P1451": _("EVAP Control System Canister Vent Solenoid Circuit Malfunction"),
    "P1452": _("Inability of Evaporative Emission Control System to Bleed Fuel Tank"),
    "P1455": _("Substantial Leak or Blockage in Evaporative Emission Control System"),
    "P1460": _("Wide Open Throttle Air Conditioning Cutoff circuit malfunction"),
    "P1461": _("Air Conditioning Pressure Sensor circuit Low Input"),
    "P1462": _("Air Conditioning Pressure Sensor circuit high Input"),
    "P1463": _("Air Conditioning Pressure Sensor Insufficient Pressure change"),
    "P1464": _("ACCS to PCM High During Self-Test"),
    "P1469": _("Low Air Conditioning Cycling Period"),
    "P1473": _("Fan Secondary High with Fans Off"),
    "P1474": _("Low Fan Control Primary circuit"),
    "P1479": _("High Fan Control Primary circuit"),
    "P1480": _("Fan Secondary Low with Low Fans On"),
    "P1481": _("Fan Secondary Low with High Fans On"),
    "P1483": _("Power to Cooling Fan Exceeded Normal Draw"),
    "P1484": _("Variable Load Control Module Pin 1 Open"),
    "P1500": _("Vehicle Speed Sensor Intermittent"),
    "P1501": _("Programmable Speedometer & Odometer Module/Vehicle Speed Sensor Intermittent circuit-failure"),
    "P1502": _("Invalid or Missing Vehicle Speed Message or Brake Data"),
    "P1504": _("Intake Air Control circuit malfunction"),
    "P1505": _("Idle Air Control System at Adaptive Clip"),
    "P1506": _("Idle Air Control Over Speed Error"),
    "P1507": _("Idle Air Control Under Speed Error"),
    "P1512": _("Intake Manifold Runner Control Stuck Closed"),
    "P1513": _("Intake Manifold Runner Control Stuck Closed"),
    "P1516": _("Intake Manifold Runner Control Input Error"),
    "P1517": _("Intake Manifold Runner Control Input Error"),
    "P1518": _("Intake Manifold Runner Control fault - Stuck Open"),
    "P1519": _("Intake Manifold Runner Control fault - Stuck Closed"),
    "P1520": _("Intake Manifold Runner Control fault"),
    "P1530": _("Open or Short to A/C Compressor Clutch circuit"),
    "P1537": _("Intake Manifold Runner Control Stuck Open"),
    "P1538": _("Intake Manifold Runner Control Stuck Open"),
    "P1539": _("Power to A/C Compressor Clutch circuit Exceeded Normal Current Draw"),
    "P1549": _("Intake Manifold Temperature Valve Vacuum Actuator Connection"),
    "P1550": _("Power Steering Pressure Sensor out of Self-Test Range"),
    "P1605": _("PCM Keep Alive Memory Test Error"),
    "P1625": _("Voltage to Vehicle Load Control Module Fan circuit not detected"),
    "P1626": _("Voltage to Vehicle Load Control Module circuit not detected"),
    "P1650": _("Power Steering Pressure Switch out of Self-Test Range"),
    "P1651": _("Power Steering Pressure Switch Input fault"),
    "P1700": _("Transmission system problems"),
    "P1701": _("Reverse Engagement Error"),
    "P1702": _("Transmission system problems"),
    "P1703": _("Brake On/Off Switch out of Self-Test Range"),
    "P1704": _("Transmission system problems"),
    "P1705": _("Manual Lever Position Sensor out of Self-Test Range"),
    "P1709": _("Park or Neutral Position Switch out of Self-Test Range"),
    "P1710": _("Transmission system problems"),
    "P1711": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1713": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1714": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1715": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1716": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1717": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1718": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1719": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1720": _("Transmission Fluid Temperature Sensor out of Self-Test Range"),
    "P1729": _("4x4 Low Switch Error"),
    "P1740": _("Transmission system problems"),
    "P1741": _("Torque Converter Clutch Control Error"),
    "P1742": _("Torque Converter Clutch Solenoid Faulty"),
    "P1743": _("Torque Converter Clutch Solenoid Faulty"),
    "P1744": _("Torque Converter Clutch System Stuck in Off Position"),
    "P1745": _("Transmission system problems"),
    "P1746": _("Electronic Pressure Control Solenoid - Open circuit"),
    "P1747": _("Electronic Pressure Control Solenoid - Short circuit"),
    "P1749": _("Electronic Pressure Control Solenoid Failed Low"),
    "P1751": _("Shift Solenoid No. 1 Performance"),
    "P1754": _("Coast Clutch Solenoid circuit malfunction"),
    "P1756": _("Shift Solenoid No. 2 Performance"),
    "P1760": _("Transmission system problems"),
    "P1761": _("Shift Solenoid No. 3 Performance"),
    "P1762": _("Transmission system problems"),
    "P1767": _("Transmission system problems"),
    "P1780": _("Transmission Control Switch circuit is out of Self-Test Range"),
    "P1781": _("4x4 Low Switch is out of Self-Test Range"),
    "P1783": _("Transmission Over-Temperature Condition"),
    "P1784": _("Transmission system problems"),
    "P1785": _("Transmission system problems"),
    "P1786": _("Transmission system problems"),
    "P1787": _("Transmission system problems"),
    "P1788": _("Transmission system problems"),
    "P1789": _("Transmission system problems"),
    "P1900": _("Transmission system problems"),
}
