#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
#
# jaguar_codes.py
#
# Copyright (C) Ben Van Mechelen 2008-2009 <me@benvm.be>
# 
# This file is part of Garmon 
# 
# Garmon is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, write to:
#   The Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor
#   Boston, MA  02110-1301, USA.


from gettext import gettext as _

DTC_CODES_MANUFACTURER = {
    "P1100": _("MAF Sensor Intermittent/ Check of all OBDII Systems Not Complete"),
    "P1101": _("MAF Sensor Out Of Self Test Range./KOER Not Able To Complete KOER Aborted"),
    "P1102": _("MAF Sensor In Range But Lower Than Expected"),
    "P1103": _("MAF Sensor In Range But Higher Than Expected"),
    "P1104": _("MAF Ground Malfunction"),
    "P1105": _("Dual Alternator Upper Fault"),
    "P1106": _("Dual Alternator Lower Fault/ Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent High Voltage"),
    "P1107": _("Dual Alternator Lower Circuit Malfunction/ Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent Low Voltage"),
    "P1108": _("Dual Alternator Battery Lamp Circuit Malfunction"),
    "P1109": _("IAT - B Sensor Intermittent"),
    "P1110": _("IAT Sensor (D/C) Open/Short"),
    "P1111": _("Intake Air Temperature (IAT) Sensor Circuit Intermittent High Voltage"),
    "P1112": _("Intake Air Temperature (IAT) Sensor Circuit Intermittent Low Voltage"),
    "P1113": _("IAT Sensor Open/Short"),
    "P1114": _("Engine Coolant Temperature (ECT) Sensor Circuit Intermittent Low Voltage/IAT - B Circuit Low Input"),
    "P1115": _("Engine Coolant Temperature (ECT) Sensor Circuit Intermittent High Voltage/IAT - B Circuit High Input"),
    "P1116": _("Engine Coolant sensor out of range/ECT Sensor Out Of Self Test Range"),
    "P1117": _("Engine Coolant Sensor intermittent/ECT Sensor Intermittent"),
    "P1118": _("Manifold Absolute Temperature Circuit Low Input"),
    "P1119": _("Manifold Absolute Temperature Circuit High Input"),
    "P1120": _("Throttle position sensor out of range"),
    "P1121": _("Throttle Position (TP) Sensor Circuit Intermittent High Voltage"),
    "P1122": _("Throttle Position (TP) Sensor Circuit Intermittent Low Voltage"),
    "P1123": _("Throttle Position Sensor In Range But Higher Than Expected"),
    "P1124": _("Throttle Position Sensor Out Of Self Test Range"),
    "P1125": _("Throttle position sensor intermittent"),
    "P1126": _("Throttle Position (Narrow Range) Sensor Circuit Malfunction"),
    "P1127": _("Exhaust Not Warm, Downstream O2 Sensor"),
    "P1128": _("Upstream Heated O2 Sensors Swapped"),
    "P1129": _("Downstream Heated O2 Sensors Swapped"),
    "P1130": _("Lack Of HO2S Switch - Adaptive Fuel At Limit"),
    "P1131": _("Lack Of HO2S Switch - Sensor Indicates Lean"),
    "P1132": _("Lack Of HO2S Switch - Sensor Indicates Rich"),
    "P1133": _("HO2S Insufficient Switching Sensor 1"),
    "P1134": _("HO2S Transition Time Ratio Sensor 1"),
    "P1135": _("Pedal Position Sensor A Circuit Intermittent"),
    "P1136": _("Fan Control Circuit Malfunction"),
    "P1137": _("Lack Of HO2S Switch - Sensor Indicates Lean"),
    "P1138": _("Lack Of HO2S12 Switch - Sensor Indicates Rich"),
    "P1139": _("Water In Fuel Indicator Circuit Malfunction"),
    "P1140": _("Water In Fuel Condition"),
    "P1141": _("Fuel Restriction Indicator Circuit Malfunction"),
    "P1142": _("Fuel Restriction Condition"),
    "P1143": _("Air Assist Control Valve Range/Performance"),
    "P1144": _("Air Assist Control Valve Circuit Malfunction"),
    "P1150": _("Lack Of HO2S21 Switch - Adaptive Fuel At Limit"),
    "P1151": _("Lack Of HO2S21 Switch - Sensor Indicates Lean"),
    "P1152": _("Lack Of HO2S21 Switch - Sensor Indicates Rich"),
    "P1153": _("Bank 2 Fuel Control Shifted Lean"),
    "P1154": _("Bank 2 Fuel Control Shifted Rich"),
    "P1155": _("Alternative Fuel Controller"),
    "P1156": _("Fuel Select Switch Malfunction"),
    "P1157": _("Lack Of HO2S22 Switch - Sensor Indicates Lean"),
    "P1158": _("Lack Of HO2S22 Switch - Sensor Indicates Rich"),
    "P1159": _("Fuel Stepper Motor Malfunction"),
    "P1167": _("Invalid Test,throttle not depressed"),
    "P1168": _("Fuel Rail Sensor In-Range Low Failure"),
    "P1169": _("Fuel Rail Sensor In-Range High Failure"),
    "P1170": _("ESO - Engine Shut Off Solenoid Fault"),
    "P1171": _("Rotor Sensor Fault"),
    "P1172": _("Rotor Control Fault"),
    "P1173": _("Rotor Calibration Fault"),
    "P1174": _("Cam Sensor Fault"),
    "P1175": _("Cam Control Fault"),
    "P1176": _("Cam Calibration Fault"),
    "P1177": _("Synchronization Fault"),
    "P1178": _("( open )"),
    "P1180": _("Fuel Delivery System Malfunction - Low"),
    "P1181": _("Fuel Delivery System Malfunction - High"),
    "P1182": _("Fuel Shut Off Solenoid Malfunction"),
    "P1183": _("Engine Oil Temperature Circuit Malfunction"),
    "P1184": _("Engine Oil Temperature Out Of Self Test Range"),
    "P1185": _("FTS High - Fuel Pump Temperature Sensor High"),
    "P1186": _("FTS Low - Fuel Pump Temperature Sensor Low"),
    "P1187": _("Variant Selection"),
    "P1188": _("Calibration Memory Fault"),
    "P1189": _("Pump Speed Signal Fault"),
    "P1190": _("Calibration Resistor Out Of Range"),
    "P1191": _("Key Line Voltage"),
    "P1192": _("Voltage External"),
    "P1193": _("EGR Drive Overcurrent"),
    "P1194": _("ECU A/D Converter"),
    "P1195": _("SCP HBCC Failed To Initialize"),
    "P1196": _("Key Off Voltage High"),
    "P1197": _("Key Off Voltage Low"),
    "P1198": _("Pump Rotor Control Underfueling"),
    "P1199": _("Fuel Level Input Circuit Low"),
    "P1200": _("Injector Control Circuit"),
    "P1201": _("Injector Circuit Open / Shorted - Cylinder #1"),
    "P1202": _("Injector Circuit Open / Shorted - Cylinder #2"),
    "P1203": _("Injector Circuit Open / Shorted - Cylinder #3"),
    "P1204": _("Injector Circuit Open / Shorted - Cylinder #4"),
    "P1205": _("Injector Circuit Open / Shorted - Cylinder #5"),
    "P1206": _("Injector Circuit Open / Shorted - Cylinder #6"),
    "P1209": _("Injector Control Pressure System Fault"),
    "P1210": _("Injector Control Pressure Above Expected Level"),
    "P1211": _("Injector Control Pressure Sensor Above / Below Desired"),
    "P1212": _("Injector Control Pressure Not Detected During Crank"),
    "P1213": _("Start Injector Circuit Malfunction"),
    "P1214": _("Pedal Position Sensor B Circuit Intermittent"),
    "P1215": _("Pedal Position Sensor C Circuit Low Input"),
    "P1216": _("Pedal Position Sensor C Circuit High Input"),
    "P1217": _("Pedal Position Sensor C Circuit Intermittent"),
    "P1218": _("CID High"),
    "P1219": _("CID Low"),
    "P1220": _("Series Throttle Control System Malfunction"),
    "P1221": _("Traction Control System Malfunction"),
    "P1222": _("Traction Control Output Circuit Malfunction"),
    "P1223": _("Pedal Demand Sensor B Circuit High Input"),
    "P1224": _("Throttle Position Sensor B Out Of Self Test Range"),
    "P1225": _("Needle Lift Sensor Malfunction"),
    "P1226": _("Control Sleeve Sensor Malfunction"),
    "P1227": _("Wastegate Failed Closed (Over Pressure)"),
    "P1228": _("Wastegate Failed Open (Under Pressure)"),
    "P1229": _("Intercooler Pump Driver Fault"),
    "P1230": _("Fuel Pump Low Speed Malfunction"),
    "P1231": _("Fuel Pump Secondary Circuit Low, High Speed"),
    "P1232": _("Fuel Pump Speed Primary Circuit Malfunction"),
    "P1233": _("Fuel Pump Driver Module Off Line"),
    "P1234": _("Fuel Pump Driver Module Off Line"),
    "P1235": _("Fuel Pump Control Out Of Range"),
    "P1236": _("Fuel Pump Control Out Of Range"),
    "P1237": _("Fuel Pump Secondary Circuit Malfunction"),
    "P1238": _("Fuel Pump Secondary Circuit Malfunction"),
    "P1239": _("Speed Fuel Pump Positive Feed Fault"),
    "P1240": _("Sensor Power Supply Malfunction"),
    "P1241": _("Sensor Power Supply Low Input"),
    "P1242": _("Sensor Power Supply High Input"),
    "P1243": _("Second Fuel Pump Faulty or Ground Fault"),
    "P1244": _("Alternator Load Input Failed High"),
    "P1245": _("Alternator Load Input Failed Low"),
    "P1246": _("Alternator Load Input Failed"),
    "P1247": _("Turbo Boost Pressure Low"),
    "P1248": _("Turbo Boost Pressure Not Detected"),
    "P1249": _("Wastegate Control Valve Performance"),
    "P1250": _("PRC Solenoid Circuit Malfunction"),
    "P1251": _("Air Mixture Solenoid Circuit Malfunction"),
    "P1252": _("Pedal Correlation PDS1 and LPDS High"),
    "P1253": _("Pedal Correlation PDS1 and LPDS Low"),
    "P1254": _("Pedal Correlation PDS2 and LPDS High"),
    "P1255": _("Pedal Correlation PDS2 and LPDS Low"),
    "P1256": _("Pedal Correlation PDS1 and HPDS"),
    "P1257": _("Pedal Correlation PDS2 and HPDS"),
    "P1258": _("Pedal Correlation PDS1 and PDS2"),
    "P1259": _("Immobilizer to PCM Signal Error"),
    "P1260": _("THEFT Detected, Vehicle Immobilzed"),
    "P1261": _("Cylinder #1 High To Low Side Short"),
    "P1262": _("Cylinder #2 High To Low Side Short"),
    "P1263": _("Cylinder #3 High To Low Side Short"),
    "P1264": _("Cylinder #4 High To Low Side Short"),
    "P1265": _("Cylinder #5 High To Low Side Short"),
    "P1266": _("Cylinder #6 High To Low Side Short"),
    "P1267": _("Cylinder #7 High To Low Side Short"),
    "P1268": _("Cylinder #8 High To Low Side Short"),
    "P1269": _("Immobilizer Code Not Programmed"),
    "P1270": _("Engine RPM Or Speed Limiter Reached"),
    "P1271": _("Cylinder #1 High To Low Side Open"),
    "P1272": _("Cylinder #2 High To Low Side Open"),
    "P1273": _("Cylinder #3 High To Low Side Open"),
    "P1274": _("Cylinder #4 High To Low Side Open"),
    "P1275": _("Cylinder #5 High To Low Side Open"),
    "P1276": _("Cylinder #6 High To Low Side Open"),
    "P1277": _("Cylinder #7 High To Low Side Open"),
    "P1278": _("Cylinder #8 High To Low Side Open"),
    "P1280": _("Injection Control Pressure Out Of Range Low"),
    "P1281": _("Injection Control Pressure Out Of Range High"),
    "P1282": _("Excessive Injection Control Pressure"),
    "P1283": _("IPR Circuit Failure"),
    "P1284": _("Aborted KOER - ICP Failure"),
    "P1285": _("Cylinder head over temp sensed"),
    "P1286": _("Fuel Pulse In Range But Lower Than Expected"),
    "P1287": _("Fuel Pulse In Range But Higher Than Expected"),
    "P1288": _("Cylinder Head Temp Sensor Out Of Self Test Range"),
    "P1289": _("Cylinder Head Temp Sensor High Input"),
    "P1290": _("Cylinder Head Temp Sensor Low Input"),
    "P1291": _("Injector High Side Short To GND Or VBATT - Bank 1"),
    "P1292": _("Injector High Side Short To GND Or VBATT - Bank 2"),
    "P1293": _("Injector High Side Open - Bank 1"),
    "P1294": _("Injector High Side Open - Bank 2/Target idle not reached"),
    "P1295": _("Multi-faults - Bank 1 - With Low Side Shorts"),
    "P1296": _("Multi-faults - Bank 2 - With Low Side Shorts"),
    "P1297": _("Injector High Sides Shorted Together"),
    "P1298": _("IDM Failure"),
    "P1299": _("Cylinder Head Overtemperature Protection Active"),
    "P1300": _("Boost Calibration Fault"),
    "P1301": _("Boost Calibration High"),
    "P1302": _("Boost Calibration Low"),
    "P1303": _("EGR Calibration Fault"),
    "P1304": _("EGR Calibration High"),
    "P1305": _("EGR Calibration Low"),
    "P1306": _("Kickdown Relay Pull - In Circuit Fault"),
    "P1307": _("Kickdown Relay Hold Circuit Fault"),
    "P1308": _("A/C Clutch Circuit Fault"),
    "P1309": _("Misfire Monitor AICE Chip Fault"),
    "P1313": _("Misfire Rate Catalyst Damage Fault - Bank 1"),
    "P1314": _("Misfire Rate Catalyst Damage Fault - Bank 2"),
    "P1315": _("Persistent Misfire"),
    "P1316": _("Injector Circuit / IDM Codes Detected"),
    "P1317": _("Injector Circuit / IDM Codes Not Updated"),
    "P1336": _("Crank / Cam Sensor Range / Performance"),
    "P1340": _("Camshaft Position Sensor B Circuit Malfunction"),
    "P1341": _("Camshaft Position Sensor B Range / Performance"),
    "P1345": _("SGC (Cam Position) Sensor Circuit Malfunction/ Crankshaft Position - Camshaft Position Correlation"),
    "P1346": _("Fuel Level Sensor B Circuit Malfunction"),
    "P1347": _("Fuel Level Sensor B Range / Performance"),
    "P1348": _("Fuel Level Sensor B Circuit Low"),
    "P1349": _("Fuel Level Sensor B Circuit High"),
    "P1350": _("Fuel Level Sensor B Intermittent/Bypass Line Monitor"),
    "P1351": _("IDM Input Circuit Malfunction/ Ignition Coil Control Circuit High Voltage"),
    "P1352": _("Ignition Coil A Primary Circuit Malfunction"),
    "P1353": _("Ignition Coil B Primary Circuit Malfunction"),
    "P1354": _("Ignition Coil C Primary Circuit Malfunction"),
    "P1355": _("Ignition Coil D Primary Circuit Malfunction"),
    "P1360": _("Ignition Coil A Secondary Circuit Malfunction"),
    "P1361": _("Ignition Control (IC) Circuit Low Voltage"),
    "P1362": _("Ignition Coil C Secondary Circuit Malfunction"),
    "P1363": _("Ignition Coil D Secondary Circuit Malfunction"),
    "P1364": _("Ignition Coil Primary Circuit Failure"),
    "P1365": _("Ignition Coil Secondary Circuit Failure"),
    "P1366": _("Ignition Spare"),
    "P1367": _("Ignition Spare"),
    "P1368": _("Ignition Spare"),
    "P1369": _("Engine Temperature Light Monitor Failure"),
    "P1370": _("Insufficient RMP Increase During Spark Test"),
    "P1371": _("Ignition Coil - Cylinder 1 - Early Activation Fault"),
    "P1372": _("Ignition Coil - Cylinder 2 - Early Activation Fault"),
    "P1373": _("Ignition Coil - Cylinder 3 - Early Activation Fault"),
    "P1374": _("Crankshaft Position (CKP)/Ignition Coil - Cylinder 4 - Early Activation Fault"),
    "P1375": _("Ignition Coil - Cylinder 5 - Early Activation Fault"),
    "P1376": _("Ignition Coil - Cylinder 6 - Early Activation Fault"),
    "P1380": _("Misfire Detected - Rough Road Data Not Available"),
    "P1381": _("Variable Cam Timing Overadvanced (Bank #1)/ Misfire Detected - No Communication with BCM"),
    "P1382": _("Variable Cam Timing Solenoid #1 Circuit Malfunction"),
    "P1383": _("Variable Cam Timing Overretarded (Bank #1)"),
    "P1384": _("VVT Solenoid A Malfunction"),
    "P1385": _("Variable Cam Timing Solenoid B Malfunction"),
    "P1386": _("Variable Cam Timing Overadvanced (Bank #2)"),
    "P1387": _("Variable Cam Timing Solenoid #2 Circuit Malfunction"),
    "P1388": _("Variable Cam Timing Overretarded (Bank #2)"),
    "P1389": _("Glow Plug Circuit High Side Low Input"),
    "P1390": _("Octane Adjust Pin Out Of Self Test Range"),
    "P1391": _("Glow Plug Circuit Low Input (Bank #1)"),
    "P1392": _("Glow Plug Circuit High Input (Bank #1)"),
    "P1393": _("Glow Plug Circuit Low Input (Bank #2)"),
    "P1394": _("Glow Plug Circuit High Input (Bank #2)"),
    "P1395": _("Glow Plug Monitor Fault (Bank #1)"),
    "P1396": _("Glow Plug Monitor Fault (Bank #2)"),
    "P1397": _("System Voltage Out Of Self Test Range"),
    "P1398": _("VVT Solenoid B Circuit High Input"),
    "P1399": _("Glow Plug Circuit High Side, High Input"),
    "P1400": _("DPFE Circuit Low Input"),
    "P1401": _("DPFE Circuit High Input"),
    "P1402": _("EGR Metering Orifice Restricted"),
    "P1403": _("DPFE Sensor Hoses Reversed"),
    "P1404": _("IAT - B Circuit Malfunction/ Exhaust Gas Recirculation Closed Position Performance"),
    "P1405": _("DPFE Sensor Upstream Hose Off Or Plugged"),
    "P1406": _("Exhaust Gas Recirculation (EGR) Position Sensor Performance"),
    "P1407": _("EGR No Flow Detected"),
    "P1408": _("EGR Flow Out Of Self Test Range"),
    "P1409": _("EVR Control Circuit Malfunction"),
    "P1411": _("SAI System Incorrect Downstream Flow Detected"),
    "P1413": _("SAI System Monitor Circuit Low Input"),
    "P1414": _("SAI System Monitor Circuit High Input"),
    "P1415": _("Air Pump Circuit Malfunction/ (AIR) System Bank 1"),
    "P1416": _("Port Air Circuit Malfunction/ (AIR) System Bank 2"),
    "P1417": _("Port Air Relief Circuit Malfunction"),
    "P1418": _("Split Air #1 Circuit Malfunction"),
    "P1419": _("Split Air #2 Circuit Malfunction"),
    "P1420": _("Catalyst Temperature Sensor Failure"),
    "P1421": _("Catalyst Damage"),
    "P1422": _("EGI Temperature Sensor Failure"),
    "P1423": _("EGI Functionality Test Failed"),
    "P1424": _("EGI Glow Plug Primary Failure"),
    "P1425": _("EGI Glow Plug Secondary Failure"),
    "P1426": _("EGI Mini - MAF Failed Out Of Range"),
    "P1427": _("EGI Mini - MAF Failed Short Circuit"),
    "P1428": _("EGI Mini - MAF Failed Open Circuit"),
    "P1429": _("Electric Air Pump Primary Failure"),
    "P1430": _("Electric Air Pump Secondary Failure"),
    "P1433": _("A/C Refrigerant Temperature Circuit Low"),
    "P1434": _("A/C Refrigerant Temperature Circuit High"),
    "P1435": _("A/C Refrigerant Temperature Circuit Range/Performance"),
    "P1436": _("A/C Evaporator Air Temperature Circuit Low"),
    "P1437": _("A/C Evaporator Air Temperature Circuit High"),
    "P1438": _("A/C Evaporator Air Temperature Circuit Range/Performance"),
    "P1439": _("Floor Temperature Switch Circuit Malfunction"),
    "P1440": _("Purge Valve Stuck Open"),
    "P1441": _("Evaporative Emission (EVAP) System Flow During Non-Purge Chevrolet Only"),
    "P1441": _("Evaporative Emission (EVAP) System Flow During Non-Purge Oldsmobile Only"),
    "P1442": _("Evaporative Emission Control System Leak Detected"),
    "P1443": _("Evaporative Emission Control System Control Valve"),
    "P1444": _("Purge Flow Sensor Circuit Low Input"),
    "P1445": _("Purge Flow Sensor Circuit High Input"),
    "P1446": _("Evaporative Vac Solenoid Circuit Malfunction"),
    "P1447": _("ELC System Closure Valve Flow Fault"),
    "P1448": _("ELC System 2 Fault"),
    "P1449": _("Evaporative Check Solenoid Circuit Malfunction"),
    "P1450": _("Unable To Bleed Up Fuel Tank Vacuum"),
    "P1451": _("Evap Emission Control Sys Vent Control Valve Circuit"),
    "P1452": _("Unable To Bleed - Up Vacuum in Tank"),
    "P1453": _("Fuel Tank Pressure Relief Valve Malfunction"),
    "P1454": _("Evaporative System Vacuum Test Malfunction"),
    "P1455": _("Evap Emission Control Sys Leak Detected (Gross Leak/No Flow)"),
    "P1456": _("Fuel Tank Temperature Sensor Circuit Malfunction"),
    "P1457": _("Unable To Pull Vacuum In Tank"),
    "P1460": _("Wide open throttle A/C cutoff relay circuit"),
    "P1461": _("A/C pressure sensor circuit voltage low"),
    "P1462": _("A/C pressure sensor circuit voltage high"),
    "P1463": _("A/C Pressure Sensor Insufficient Pressure Change"),
    "P1464": _("A/C Demand Out of Self Test Range"),
    "P1465": _("A/C Relay Circuit Malfunction"),
    "P1466": _("A/C Refrigerant Temperature Sensor/Circuit Malfunction"),
    "P1467": _("A/C Compressor Temperature Sensor Malfunction"),
    "P1468": _("SSPOD Open Circuit or Closed Circuit Fault"),
    "P1469": _("Low A/C Cycling Period"),
    "P1470": _("A/C Cycling Period Too Short"),
    "P1471": _("Electrodrive Fan 1 Operational Failure (Driver Side)"),
    "P1472": _("Electrodrive Fan 2 Operational Failure (Passenger Side)"),
    "P1473": _("Fan Secondary High With Fan(s) Off"),
    "P1474": _("Low Fan Control Primary Circuit Malfunction"),
    "P1475": _("Fan Relay (Low) Circuit Malfunction"),
    "P1476": _("Fan Relay (High) Circuit Malfunction"),
    "P1477": _("Additional Fan Relay Circuit Malfunction"),
    "P1478": _("Cooling Fan Driver Fault"),
    "P1479": _("High Fan Control Primary Circuit Malfunction"),
    "P1480": _("Fan Secondary Low with Low Fan On"),
    "P1481": _("Fan Secondary Low With High Fan On"),
    "P1482": _("SCP"),
    "P1483": _("Power To Fan Circuit Overcurrent"),
    "P1484": _("Open Power To Ground VCRM"),
    "P1485": _("EGRV Circuit Malfunction"),
    "P1486": _("EGRA Circuit Malfunction"),
    "P1487": _("EGRCHK Solenoid Circuit Malfunction"),
    "P1490": _("Secondary Air Relief Solenoid Circuit Malfunction"),
    "P1491": _("Secondary Switch Solenoid Circuit Malfunction"),
    "P1492": _("APLSOL Solenoid Circuit Malfunction"),
    "P1493": _("RCNT Solenoid Circuit Malfunction"),
    "P1494": _("SPCUT Solenoid Circuit Malfunction"),
    "P1495": _("TCSPL Solenoid Circuit Malfunction"),
    "P1500": _("Vehicle Speed Sensor Intermittent"),
    "P1501": _("Vehicle Speed Sensor Out Of Self Test Range"),
    "P1502": _("Vehicle Speed Sensor Intermittent Malfunction"),
    "P1503": _("Auxillary Speed Sensor Fault"),
    "P1504": _("Idle Air Control Circuit Malfunction"),
    "P1505": _("Idle Air Control System At Adaptive Clip"),
    "P1506": _("Idle Air Control Overspeed Error"),
    "P1507": _("Idle Air Control Underspeed Error"),
    "P1508": _("Idle Control System Circuit Open"),
    "P1509": _("Idle Control System Circuit Shorted"),
    "P1510": _("Idle Signal Circuit Malfunction"),
    "P1511": _("Idle Switch (Electric Control Throttle) Circuit Malfunction"),
    "P1512": _("Intake Manifold Runner Control (Bank 1) Stuck Closed"),
    "P1513": _("Intake Manifold Runner Control (Bank 2) Stuck Closed"),
    "P1514": _("High Load Neutral/Drive Fault"),
    "P1515": _("Electric Current Circuit Malfunction"),
    "P1516": _("IMRC Input Error (Bank 1)"),
    "P1517": _("IMRC Input Error (Bank 2)"),
    "P1518": _("Intake Manifold Runner Control (Stuck Open)"),
    "P1519": _("Intake Manifold Runner Control (Stuck Closed)"),
    "P1520": _("Intake Manifold Runner Control Circuit Malfunction"),
    "P1521": _("Variable Intake Solenoid #1 Circuit Malfunction"),
    "P1522": _("Variable Intake Solenoid #2 Circuit Malfunction"),
    "P1523": _("IVC Solenoid Circuit Malfunction"),
    "P1524": _("Variable Intake Solenoid System"),
    "P1525": _("Air Bypass Valve System"),
    "P1526": _("Air Bypass System"),
    "P1527": _("Accelerate Warmup Solenoid Circuit Malfunction"),
    "P1528": _("Subsidiary Throttle Valve Solenoid Circuit Malfunction"),
    "P1529": _("SCAIR Solenoid Circuit Malfunction"),
    "P1530": _("A/C Clutch Circuit Malfunction"),
    "P1531": _("Invalid Test - Accelerator Pedal Movement"),
    "P1532": _("IMCC Circuit Malfunction, Bank B"),
    "P1533": _("AAI Circuit Malfunction"),
    "P1534": _("Inertia Switch Activated"),
    "P1535": _("Blower Fan Speed Circuit Range/Performance"),
    "P1536": _("Parking Brake Switch Circuit Failure"),
    "P1537": _("Intake Manifold Runner Control (Bank 1) Stuck Open"),
    "P1538": _("Intake Manifold Runner Control (Bank 2) Stuck Open"),
    "P1539": _("Power To A/C Clutch Circuit Overcurrent"),
    "P1540": _("Air Bypass Valve Circuit Malfunction"),
    "P1549": _("IMCC Circuit Malfunction, Bank B"),
    "P1550": _("PSPS Out Of Self Test Range"),
    "P1565": _("Speed Control Command Switch Out of Range High"),
    "P1566": _("Speed Control Command Switch Out of Range Low"),
    "P1567": _("Speed Control Output Circuit Continuity"),
    "P1568": _("Speed Control Unable to Hold Speed"),
    "P1571": _("Brake Switch Malfunction"),
    "P1572": _("Brake Pedal Switch Circuit Malfunction"),
    "P1573": _("Throttle Position Not Available"),
    "P1574": _("Throttle Position Sensor Disagreement btwn Sensors"),
    "P1575": _("Pedal Position Out of Self Test Range"),
    "P1576": _("Pedal Position Not Available"),
    "P1577": _("Pedal Position Sensor Disagreement btwn Sensors"),
    "P1578": _("ETC Power Less Than Demand"),
    "P1579": _("ETC In Power Limiting Mode"),
    "P1580": _("Electronic Throttle Monitor PCM Override"),
    "P1581": _("Electronic Throttle Monitor Malfunction"),
    "P1582": _("Electronic Throttle Monitor Data Available"),
    "P1583": _("Electronic Throttle Monitor Cruise Disable"),
    "P1584": _("TCU Detected IPE Circuit Malfunction"),
    "P1585": _("Throttle Control Unit Malfunction"),
    "P1586": _("Throttle Control Unit Throttle Position Malfunction"),
    "P1587": _("Throttle Control Unit Modulated Command Malfunction"),
    "P1588": _("Throttle Control Unit Detected Loss of Return Spring"),
    "P1589": _("TCU Unable To Control Desired Throttle Angle"),
    "P1600": _("Loss of KAM Power; Open Circuit"),
    "P1601": _("ECM/TCM Serial Communication Error"),
    "P1602": _("Immobilizer/ECM Communication Error"),
    "P1603": _("EEPROM Malfunction"),
    "P1604": _("Code Word Unregestered"),
    "P1605": _("Keep Alive Memory Test Failure"),
    "P1606": _("ECM Control Relay O/P Circuit Malfunction"),
    "P1607": _("MIL O/P Circuit Malfunction"),
    "P1608": _("Internal ECM Malfunction"),
    "P1609": _("Diagnostic Lamp Driver Fault"),
    "P1610": _("SBDS Interactive Codes"),
    "P1611": _("SBDS Interactive Codes"),
    "P1612": _("SBDS Interactive Codes"),
    "P1613": _("SBDS Interactive Codes"),
    "P1614": _("SBDS Interactive Codes"),
    "P1615": _("SBDS Interactive Codes"),
    "P1616": _("SBDS Interactive Codes"),
    "P1617": _("SBDS Interactive Codes"),
    "P1618": _("SBDS Interactive Codes"),
    "P1619": _("SBDS Interactive Codes"),
    "P1620": _("SBDS Interactive Codes"),
    "P1621": _("Control Module Long Term Memory Performance/ Immobilizer Code Words Do Not Match"),
    "P1622": _("Immobilizer ID Does Not Match"),
    "P1623": _("Immobilizer Code Word/ID Number Write Failure"),
    "P1624": _("Anti Theft System"),
    "P1625": _("B+ Supply To VCRM Fan Circuit Malfunction"),
    "P1626": _("Theft Deterrent Fuel Enable Signal Not Received/ B+ Supply To VCRM A/C Circuit Malfunction"),
    "P1627": _("Module Supply Voltage Out Of Range"),
    "P1628": _("Module Ignition Supply Input Malfunction"),
    "P1629": _("Internal Voltage Regulator Malfunction"),
    "P1630": _("Internal Vref Malfunction"),
    "P1631": _("Theft Deterrent Start Enable Signal Not Correct/ Main Relay Malfunction (Power Hold)"),
    "P1632": _("Smart Alternator Faults Sensor/Circuit Malfunction"),
    "P1633": _("KAM Voltage Too Low"),
    "P1634": _("Data Output Link Circuit Failure"),
    "P1635": _("Tire / Axle Ratio Out of Acceptable Range"),
    "P1636": _("Inductive Signature Chip Communication Error"),
    "P1637": _("Can Link ECM/ABSCM Circuit / Network Malfunction"),
    "P1638": _("Can Link ECM/INSTM Circuit / Network Malfunction"),
    "P1639": _("Vehicle ID Block Corrupted or Not Programmed"),
    "P1640": _("Powertrain DTCs Available in Another Module"),
    "P1641": _("Fuel Pump Primary Circuit Failure"),
    "P1642": _("Fuel Pump Monitor Circuit High Input"),
    "P1643": _("Fuel Pump Monitor Circuit Low Input"),
    "P1644": _("Fuel Pump Speed Control Circuit Malfunction"),
    "P1645": _("Fuel Pump Resistor Switch Circuit Malfunction"),
    "P1650": _("PSP Switch Out of Self Test Range"),
    "P1651": _("PSP Switch Input Malfunction"),
    "P1652": _("IAC Monitor Disabled by PSP Switch Failed On"),
    "P1653": _("Power Steering Output Circuit Malfunction"),
    "P1654": _("Recirculation Override Circuit Malfunction"),
    "P1655": _("Starter Disable Circuit Malfunction"),
    "P1660": _("Output Circuit Check Signal High"),
    "P1661": _("Output Circuit Check Signal Low"),
    "P1662": _("IDM_EN Circuit Failure"),
    "P1663": _("Fuel Demand Command Signal Circuit Malfunction"),
    "P1667": _("CI Circuit Malfunction"),
    "P1668": _("PCM - IDM Communications Error"),
    "P1670": _("Electronic Feedback Signal Not Detected"),
    "P1680": _("Metering Oil Pump Malfunction"),
    "P1681": _("Metering Oil Pump Malfunction"),
    "P1682": _("Metering Oil Pump Malfunction"),
    "P1683": _("Metering Oil Pump Temperature Sensor Circuit Malfunction"),
    "P1684": _("Metering Oil Pump Position Sensor Circuit Malfunction"),
    "P1685": _("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    "P1686": _("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    "P1687": _("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    "P1688": _("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    "P1689": _("Oil Pressure Control Solenoid Circuit Malfunction"),
    "P1690": _("Wastegate Solenoid Circuit Malfunction"),
    "P1691": _("Turbo Pressure Control Solenoid Circuit Malfunction"),
    "P1692": _("Turbo Control Solenoid Circuit Malfunction"),
    "P1693": _("Turbo Charge Control Circuit Malfunction"),
    "P1694": _("Turbo Charge Relief Circuit Malfunction"),
    "P1700": _("Transmission Indeterminate Failure (Failed to Neutral)"),
    "P1701": _("Reverse Engagement Error"),
    "P1702": _("TRS Circuit Intermittent Malfunction"),
    "P1703": _("Brake Switch Out Of Self Test Range"),
    "P1704": _("Digital TRS Failed to Transition States in KOEO / KOER"),
    "P1705": _("Not in P or N During KOEO / KOER"),
    "P1706": _("High Vehicle Speed Observed in Park"),
    "P1707": _("Transfer Case Neutral Indicator Hard Fault Present"),
    "P1708": _("Clutch Switch Circuit Malfunction"),
    "P1709": _("PNP Switch Out Of Self Test Range"),
    "P1711": _("TFT Sensor Out Of Self Test Range"),
    "P1712": _("Trans Torque Reduction Request Signal Malfunction"),
    "P1713": _("TFT Sensor In Range Failure Low Value"),
    "P1714": _("SSA Inductive Signature Malfunction"),
    "P1715": _("SSB Inductive Signature Malfunction"),
    "P1716": _("SSC Inductive Signature Malfunction"),
    "P1717": _("SSD Inductive Signature Malfunction"),
    "P1718": _("TFT Sensor In Range Failure High"),
    "P1720": _("Vehicle Speed (Meter) Circuit Malfunction"),
    "P1721": _("Gear 1 Incorrect Ratio"),
    "P1722": _("Gear 2 Incorrect Ratio"),
    "P1723": _("Gear 3 incorrect Ratio"),
    "P1724": _("Gear 4 Incorrect Ratio"),
    "P1725": _("Insufficient Engine Speed Increase During Self Test"),
    "P1726": _("Insufficient Engine Speed Decrease During Self Test"),
    "P1727": _("Coast Clutch Solenoid Inductive Signature Malfunction"),
    "P1728": _("Transmission Slip Error"),
    "P1729": _("4x4 Low Switch Error"),
    "P1730": _("Gear Control Malfunction 2,3,5"),
    "P1731": _("1-2 Shift Malfunction"),
    "P1732": _("2-3 Shift Malfunction"),
    "P1733": _("3-4 Shift Malfunction"),
    "P1734": _("Gear Control Malfunction"),
    "P1735": _("First Gear Switch Circuit Malfunction"),
    "P1736": _("Second Gear Switch Circuit Malfunction"),
    "P1737": _("Lockup Solenoid System"),
    "P1738": _("Shift Time Error"),
    "P1739": _("Slip Solenoid System"),
    "P1740": _("Torque Converter Clutch Inductive Signature Malfunction"),
    "P1741": _("Torque Converter Clutch Control Error"),
    "P1742": _("Torque Converter Clutch Solenoid Failed On"),
    "P1743": _("Torque Converter Clutch Solenoid Failied On"),
    "P1744": _("Torque Converter Clutch System Performance"),
    "P1745": _("Line Pressure Solenoid System"),
    "P1746": _("Pressure Control Solenoid 'A' Open Circuit"),
    "P1747": _("Pressure Control Solenoid 'A' Short Circuit"),
    "P1748": _("EPC Malfunction"),
    "P1749": _("Pressure Control Solenoid Failed Low"),
    "P1751": _("Shift Solenoid A Performance"),
    "P1754": _("Coast Clutch Solenoid Circuit Malfunction"),
    "P1755": _("Intermediate Speed Sensor (ISS) Malfunction"),
    "P1756": _("Shift Solenoid B Performance"),
    "P1760": _("Pressure Control Solenoid 'A' Short Circuit"),
    "P1761": _("Shift Solenoid C Performance"),
    "P1762": _("Overdrive Band Failed Off"),
    "P1765": _("Timing Solenoid Circuit Malfunction"),
    "P1767": _("Torque Converter Clutch Circuit Malfunction"),
    "P1768": _("Performance / Normal / Winter Mode Input Malfunction"),
    "P1769": _("AG4 Transmission Torque Modulation Fault"),
    "P1770": _("Clutch Solenoid Circuit Malfunction"),
    "P1775": _("Transmission System MIL Fault"),
    "P1776": _("Ignition Retard Request Duration Fault"),
    "P1777": _("Ignition Retard Request Circuit Fault"),
    "P1778": _("Transmission Reverse I/P Circuit Malfunction"),
    "P1779": _("TCIL Circuit Malfunction"),
    "P1780": _("Trans Control Switch (O/D Cancel) Out of Self Test Range"),
    "P1781": _("4X4 Switch Out of Self Test Range"),
    "P1782": _("P/ES Circuit Out Of Self Test Range"),
    "P1783": _("Transmission Overtemperature Condition"),
    "P1784": _("Transmission Mechanical Failure - First And Reverse"),
    "P1785": _("Transmission Mechanical Failure - First And Second"),
    "P1786": _("3-2 Downshift Error"),
    "P1787": _("2-1 Downshift Error"),
    "P1788": _("Pressure Control Solenoid 'B' Open Circuit"),
    "P1789": _("Pressure Control Solenoid 'B' Short Circuit"),
    "P1790": _("TP (Mechanical) Circuit Malfunction"),
    "P1791": _("TP (Electric) Circuit Malfunction"),
    "P1792": _("Barometer Pressure Circuit Malfunction"),
    "P1793": _("Intake Air Volume Circuit Malfunction"),
    "P1794": _("Battery Voltage Circuit Malfunction"),
    "P1795": _("Idle Switch Circuit Malfunction"),
    "P1796": _("Kick Down Switch Circuit Malfunction"),
    "P1797": _("Neutral Switch Circuit Malfunction"),
    "P1798": _("Coolant Temperature Circuit Malfunction"),
    "P1799": _("Hold Switch Circuit Malfunction"),
    "P1800": _("Transmission Clutch Interlock Safety Switch Circuit Failure"),
    "P1801": _("Transmission Clutch Interlock Safety Switch Open Circuit"),
    "P1802": _("Transmission Clutch Interlock Safety Switch Short Circuit To Battery"),
    "P1803": _("Transmission Clutch Interlock Safety Switch Short Circuit To Ground"),
    "P1804": _("Transmission 4-Wheel Drive High Indicator Circuit Failure"),
    "P1805": _("Transmission 4-Wheel Drive High Indicator Open Circuit"),
    "P1806": _("Transmission 4-Wheel Drive High Indicator Short Circuit To Battery"),
    "P1807": _("Transmission 4-Wheel Drive High Indicator Short Circuit To Ground"),
    "P1808": _("Transmission 4-Wheel Drive Low Indicator Circuit Failure"),
    "P1809": _("Transmission 4-Wheel Drive Low Indicator Open Circuit"),
    "P1810": _("TFP Valve Position Switch Circuit/ Transmission 4-Wheel Drive Low Indicator Short Circuit To Battery"),
    "P1811": _("Transmission 4-Wheel Drive Low Indicator Short Circuit To Ground"),
    "P1812": _("Transmission 4-Wheel Drive Mode Select Circuit Failure"),
    "P1813": _("Transmission 4-Wheel Drive Mode Select Open Circuit"),
    "P1814": _("Transmission 4-Wheel Drive Mode Select Short Circuit To Battery"),
    "P1815": _("Transmission 4-Wheel Drive Mode Select Short Circuit To Ground"),
    "P1816": _("Transmission Neutral Safety Switch Circuit Failure"),
    "P1817": _("Transmission Neutral Safety Switch Open Circuit"),
    "P1818": _("Transmission Neutral Safety Switch Short Circuit To Battery"),
    "P1819": _("Transmission Neutral Safety Switch Short Circuit To Ground"),
    "P1820": _("Transmission Transfer Case Clockwise Shift Relay Coil Circuit Failure"),
    "P1821": _("Transmission Transfer Case Clockwise Shift Relay Coil Open Circuit"),
    "P1822": _("Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Battery"),
    "P1823": _("Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Ground"),
    "P1824": _("Transmission 4-Wheel Drive Clutch Relay Circuit Failure"),
    "P1825": _("Transmission 4-Wheel Drive Clutch Relay Open Circuit"),
    "P1826": _("Transmission 4-Wheel Drive Low Clutch Relay Circuit To Battery"),
    "P1827": _("Transmission 4-Wheel Drive Low Clutch Relay Circuit To Ground"),
    "P1828": _("Transmission Transfer Case Counter Clockwise Shift Relay Coil Circuit Failure"),
    "P1829": _("Transmission Transfer Case Counter Clockwise Shift Relay Coil Open Circuit"),
    "P1830": _("Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Battery"),
    "P1831": _("Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Ground"),
    "P1832": _("Transmission Transfer Case Differential Lock-Up Solenoid Circuit Failure"),
    "P1833": _("Transmission Transfer Case Differential Lock-Up Solenoid Open Circuit"),
    "P1834": _("Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Battery"),
    "P1835": _("Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Ground"),
    "P1836": _("Transmission Transfer Case Front Shaft Speed Sensor Circuit Failure"),
    "P1837": _("Transmission Transfer Case Rear Shaft Speed Sensor Circuit Failure"),
    "P1838": _("Transmission Transfer Case Shift Motor Circuit Failure"),
    "P1839": _("Transmission Transfer Case Shift Motor Open Circuit"),
    "P1840": _("Transmission Transfer Case Shift Motor Short Circuit To Battery"),
    "P1841": _("Transmission Transfer Case Shift Motor Short Circuit To Ground"),
    "P1842": _("Transmission Transfer Case Differential Lock-Up Feedback Switch Circuit Failure"),
    "P1843": _("Transmission Transfer Case Differential Lock-Up Feedback Switch Open Circuit"),
    "P1844": _("Transmission Transfer Case Differential Lock-Up Feedback Switch Short Circuit To Battery"),
    "P1845": _("Transmission Transfer Case Differential Lock-Up Feedback Switch Short Circuit To Ground"),
    "P1846": _("Transmission Transfer Case Contact Plate 'A' Circuit Failure"),
    "P1847": _("Transmission Transfer Case Contact Plate 'A' Open Circuit"),
    "P1848": _("Transmission Transfer Case Contact Plate 'A' Short Circuit To Battery"),
    "P1849": _("Transmission Transfer Case Contact Plate 'A' Short Circuit To Ground"),
    "P1850": _("Transmission Transfer Case Contact Plate 'B' Circuit Failure"),
    "P1851": _("Transmission Transfer Case Contact Plate 'B' Open Circuit"),
    "P1852": _("Transmission Transfer Case Contact Plate 'B' Short Circuit To Battery"),
    "P1853": _("Transmission Transfer Case Contact Plate 'B' Short Circuit To Ground"),
    "P1854": _("Transmission Transfer Case Contact Plate 'C' Circuit Failure"),
    "P1855": _("Transmission Transfer Case Contact Plate 'C' Open Circuit"),
    "P1856": _("Transmission Transfer Case Contact Plate 'C' Short Circuit To Battery"),
    "P1857": _("Transmission Transfer Case Contact Plate 'C' Short Circuit To Ground"),
    "P1858": _("Transmission Transfer Case Contact Plate 'D' Circuit Failure"),
    "P1859": _("Transmission Transfer Case Contact Plate 'D' Open Circuit"),
    "P1860": _("TCC PWM Solenoid Circuit Electrical/ Transmission Transfer Case Contact Plate 'D' Short Circuit To Battery"),
    "P1861": _("Transmission Transfer Case Contact Plate 'D' Short Circuit To Ground"),
    "P1862": _("Transmission Transfer Case Contact Plate Power Circuit Failure"),
    "P1863": _("Transmission Transfer Case Contact Plate Power Open Circuit"),
    "P1864": _("Transmission Transfer Case Contact Plate Power Short To Battery"),
    "P1865": _("Transmission Transfer Case Contact Plate Power Short To Ground"),
    "P1866": _("Transmission Transfer Case System Concern - Servicing Required"),
    "P1867": _("Transmission Transfer Case Contact Plate General Circuit Failure"),
    "P1868": _("Transmission Automatic 4-Wheel Drive Indicator (Lamp) Circuit Failure"),
    "P1869": _("Transmission Automatic 4-Wheel Drive Indicator (Lamp) Circuit Short To Battery"),
    "P1870": _("Transmission Component Slipping/ Transmission Mechanical Transfer Case 4x4 Switch Circuit Failure"),
    "P1871": _("Transmission Mechanical Transfer Case 4x4 Switch Circuit Short To Battery"),
    "P1872": _("Transmission Mechanical 4-Wheel Drive Axle Lock Lamp Circuit Failure"),
    "P1873": _("Transmission Mechanical 4-Wheel Drive Axle Lock Lamp Circuit Short To Battery"),
    "P1874": _("Transmission Automatic Hall Effect Sensor Power Circuit Failure"),
    "P1875": _("Transmission Automatic Hall Effect Sensor Power Circuit Short To Battery / 4WD Low Switch Circuit Electrical"),
    "P1876": _("Transmission Transfer Case 2-Wheel Drive Solenoid Circuit Failure"),
    "P1877": _("Transmission Transfer Case 2-Wheel Drive Solenoid Circuit Short To Battery"),
    "P1878": _("Transmission Transfer Case Disengaged Solenoid Circuit Failure"),
    "P1879": _("Transmission Transfer Case Disengaged Solenoid Open Circuit"),
    "P1880": _("Transmission Transfer Case Disengaged Solenoid Short to Battery"),
    "P1881": _("Engine Coolant Level Switch Circuit Failure, GEM"),
    "P1882": _("Engine Coolant Level Switch Circuit Short to Ground"),
    "P1883": _("Engine Coolant Level Switch Circuit Failure, GEM"),
    "P1884": _("Engine Coolant Level Lamp Circuit Short to Ground"),
    "P1885": _("Transmission Transfer Case Disengaged Solenoid Short to Ground"),
    "P1886": _("4X4 Initialization Failure"),
    "P1890": _("Transmission 4WD Mode Select Return Input Circuit Failure"),
    "P1891": _("Transmission Transfer Case Contact Plate Ground Return Open Circuit"),
    "P1900": _("OSS Circuit Intermittent Malfunction"),
    "P1901": _("TSS Circuit Intermittent Malfunction"),
    "P1902": _("Pressure Control Solenoid 'B' Intermittent Short"),
    "P1903": _("Pressure Control Solenoid 'C' Short Circuit"),
    "P1904": _("Pressure Control Solenoid 'C' Open Circuit"),
    "P1905": _("Pressure Control Solenoid 'C' Intermittent Short"),
    "P1906": _("Kickdown Pull Relay Open or Short Circuit to Ground"),
    "P1907": _("Kickdown Hold Relay Open or Short Circuit to Ground"),
    "P1908": _("Transmission Pressure Circuit Solenoid Open or Short to Ground"),
    "P1909": _("Trans Temp Sensor Circuit Open or Shorted to Pwr or Gnd"),
    "P1910": _("VFS A Pressure Output Failed Low"),
    "P1911": _("VFS B Pressure Output Failed Low"),
    "P1912": _("VFS C Pressure Output Failed Low"),
    "P1913": _("Pressure Switch A Circuit Malfunction"),
    "P1914": _("Manually Shifted Automatic (MSA) Sw Circuit Malf"),
    "P1915": _("Reverse Switch Circuit Malfunction"),
    "P1916": _("High Clutch Drum Speed Sensor Malfunction"),
    "P1917": _("High Clutch Drum Speed Sensor Intermittent"),
    "P1918": _("Transmission Range Display Circuit Malfunction"),
}
