#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
#
# land_rover_codes.py
#
# Copyright (C) Ben Van Mechelen 2008-2009 <me@benvm.be>
# 
# This file is part of Garmon 
# 
# Garmon is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, write to:
#   The Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor
#   Boston, MA  02110-1301, USA.


from gettext import gettext as _

DTC_CODES_MANUFACTURER = {
    "P0101": _("Mass Air Flow Sensor Signal Error Fault"),
    "P0102": _("Mass Air Flow Sensor Low Out of Range Fault"),
    "P0103": _("Mass Air Flow Sensor High Out of Range Fault"),
    "P0111": _("Air Temperature Sensor Signal Error Fault"),
    "P0112": _("Air Temperature Sensor Low Out of Range Fault"),
    "P0113": _("Air Temperature Sensor High Out of Range Fault"),
    "P0116": _("Engine Coolant Temperature Sensor Falling Temp Fault"),
    "P0117": _("Engine Coolant Temperature Sensor Low Out of Range Fault"),
    "P0118": _("Engine Coolant Temperature Sensor High Out of Range Fault"),
    "P0121": _("Throttle Position Sensor Output Signal Error Fault"),
    "P0122": _("Throttle Position Sensor Low Out of Range Fault"),
    "P0123": _("Throttle Position Sensor High Out of Range Fault"),
    "P0125": _("Engine Coolant Temp Sensor Warm Up Fault"),
    "P0130": _("Oxygen Sensor Cycle Fault *Codes* A U"),
    "P0131": _("Oxygen Sensor Low Voltage *Codes* A U"),
    "P0132": _("Oxygen Sensor High Voltage *Codes* A U"),
    "P0133": _("Oxygen Sensor Slow Response *Codes* A U"),
    "P0136": _("Oxygen Sensor Cycle Fault *Codes* A D"),
    "P0137": _("Oxygen Sensor Low Voltage *Codes* A D"),
    "P0138": _("Oxygen Sensor High Voltage *Codes* A D"),
    "P0139": _("Oxygen Sensor Slow Response *Codes* A D"),
    "P0150": _("Oxygen Sensor Cycle Fault *Codes* B U"),
    "P0151": _("Oxygen Sensor Low Voltage *Codes* B U"),
    "P0152": _("Oxygen Sensor High Voltage *Codes* B U"),
    "P0153": _("Oxygen Sensor Slow Response *Codes* B U"),
    "P0156": _("Oxygen Sensor Cycle Fault *Codes* B D"),
    "P0157": _("Oxygen Sensor Low Voltage *Codes* B D"),
    "P0158": _("Oxygen Sensor High Voltage *Codes* B D"),
    "P0159": _("Oxygen Sensor Slow Response *Codes* B D"),
    "P0171": _("Oxygen Sensor System Too Lean Fault Bank A"),
    "P0172": _("Oxygen Sensor System Too Rich Fault Bank A"),
    "P0174": _("Oxygen Sensor System Too Lean Fault Bank B"),
    "P0175": _("Oxygen Sensor System Too Rich Fault Bank B"),
    "P0181": _("Fuel Temperature Sensor Signal Error Fault"),
    "P0182": _("Fuel Temperature Sensor Low Out of Range Fault"),
    "P0183": _("Fuel Temperature Sensor High Out of Range Fault"),
    "P0201": _("Injector 1 Circuit Fault"),
    "P0202": _("Injector 2 Circuit Fault"),
    "P0203": _("Injector 3 Circuit Fault"),
    "P0204": _("Injector 4 Circuit Fault"),
    "P0205": _("Injector 5 Circuit Fault"),
    "P0206": _("Injector 6 Circuit Fault"),
    "P0207": _("Injector 7 Circuit Fault"),
    "P0208": _("Injector 8 Circuit Fault"),
    "P0300": _("Misfire On Multiple Cylinder"),
    "P0301": _("Misfire Cylinder 1"),
    "P03O2": _("Misfire Cylinder 2"),
    "P03O3": _("Misfire Cylinder 3"),
    "P0304": _("Misfire Cylinder 4"),
    "P0305": _("Misfire Cylinder 5"),
    "P0306": _("Misfire Cylinder 6"),
    "P0307": _("Misfire Cylinder 7"),
    "P0308": _("Misfire Cylinder 8"),
    "P0326": _("Continuous Knock Fault Bank A"),
    "P0327": _("Background Noise Low Fault Bank A"),
    "P0328": _("Background Noise High Fault Bank A"),
    "P0331": _("Continuous Knock Fault Bank B"),
    "P0332": _("Background Noise Low Fault Bank B"),
    "P0333": _("Background Noise High Fault Bank B"),
    "P0335": _("Crankshaft Position Sensor Signal Error Fault"),
    "P0336": _("Crankshaft Position Sensor Out of Range Fault"),
    "P0340": _("Camshaft Position Sensor Signal Error Fault"),
    "P0420": _("Catalyst Efficiency Low Fault Bank A"),
    "P0430": _("Catalyst Efficiency Low Fault Bank B"),
    "P0441": _("Evap Purge Valve Incorrect Flow Fault"),
    "P0442": _("Evap System Small Leak Detected Fault"),
    "P0443": _("Evap Purge Valve Open or Short Circuit Fault"),
    "P0451": _("Fuel Tank Pressure Sensor Signal Error Fault"),
    "P0452": _("Fuel Tank Pressure Sensor Low out of Range Fault"),
    "P0453": _("Fuel Tank Pressure Sensor High Out of Range Fault"),
    "P0461": _("Fuel Tank Level Measurement Not Valid Fault"),
    "P0500": _("Vehicle Speed Sensor Signal Error Fault"),
    "P0506": _("Idle Speed Control Engine Speed Low Fault"),
    "P0507": _("Idle Speed Control Engine Speed High Fault"),
    "P0560": _("Battery Voltage Below Minimum Fault"),
    "P0562": _("Measurement Circuit OK Battery Voltage Low Fault"),
    "P0563": _("Battery Voltage Above Maximum Fault"),
    "P0605": _("ECM Self Test Fault"),
    "P1130": _("Oxygen Sensor Fuel Trim at Limit *Codes* A U"),
    "P1131": _("Oxygen Sensor Engine Lean *Codes* A U"),
    "P1132": _("Oxygen Sensor Engine Rich *Codes* A U"),
    "P1137": _("Oxygen Sensor Engine Lean *Codes* A D"),
    "P1138": _("Oxygen Sensor Engine Rich *Codes* A D"),
    "P1150": _("Oxygen Sensor Fuel Trim at Limit *Codes* B U"),
    "P1151": _("Oxygen Sensor Engine Lean *Codes* B U"),
    "P1152": _("Oxygen Sensor Engine Rich *Codes* B U"),
    "P1157": _("Oxygen Sensor Engine Lean *Codes* B D"),
    "P1158": _("Oxygen Sensor Engine Rich *Codes* B D"),
    "P1171": _("Oxygen Sensor System Too Lean Fault Banks A & B"),
    "P1172": _("Oxygen Sensor System Too Rich Fault Banks A & B"),
    "P1176": _("Maximum Positive FMFR Correction Fault"),
    "P1177": _("Maximum Negative FMFR Correction Fault"),
    "P1178": _("Maximum Positive AMFR Correction Fault"),
    "P1179": _("Maximum Negative AMFR Correction Fault"),
    "P1185": _("Oxygen Sensor Heater Circuit Open Upstream"),
    "P1186": _("Oxygen Sensor Heater Circuit Short Upstream"),
    "P1187": _("Oxygen Sensor Heater Circuit Short Upstream"),
    "P1188": _("Oxygen Sensor Heater High Resistance Upstream"),
    "P1189": _("Oxygen Sensor Heater Type 1 Low Resistance Upstream"),
    "P1190": _("Oxygen Sensor Heater Type 2 Low Resistance Upstream"),
    "P1191": _("Oxygen Sensor Heater Circuit Open Downstream"),
    "P1192": _("Oxygen Sensor Heater Circuit Short Downstream"),
    "P1193": _("Oxygen Sensor Heater Circuit Open Downstream"),
    "P1194": _("Oxygen Sensor Heater High Resistance Downstream"),
    "P1195": _("Oxygen Sensor Heater Type 1 Low Resistance Downstream"),
    "P1196": _("Oxygen Sensor Heater Type 2 Low Resistance Downstream"),
    "P1199": _("Fuel Level Sensor Circuit Fault"),
    "P1201": _("Injector 1 Open Circuit or Ground Short Fault"),
    "P1202": _("Injector 2 Open Circuit or Ground Short Fault"),
    "P1203": _("Injector 3 Open Circuit or Ground Short Fault"),
    "P1204": _("Injector 4 Open Circuit or Ground Short Fault"),
    "P1205": _("Injector 5 Open Circuit or Ground Short Fault"),
    "P1206": _("Injector 6 Open Circuit or Ground Short Fault"),
    "P1207": _("Injector 7 Open Circuit or Ground Short Fault"),
    "P1208": _("Injector 8 Open Circuit or Ground Short Fault"),
    "P1313": _("Misfire Catalyst Damage Fault Bank A"),
    "P1314": _("Misfire Catalyst Damage Fault Bank B"),
    "P1315": _("Misfire Persistent Fault"),
    "P1316": _("Misfire Excessive Emissions Fault"),
    "P1317": _("ABS Rough Road Line Low Fault"),
    "P1318": _("ABS Rough Road Line High Fault"),
    "P1361": _("No Ignition Coil Activation Fault Coil 1"),
    "P1362": _("No Ignition Coil Activation Fault Coil 2"),
    "P1363": _("No Ignition Coil Activation Fault Coil 3"),
    "P1364": _("No Ignition Coil Activation Fault Coil 4"),
    "P1371": _("Early Ignition Coil Activation Fault Coil 1"),
    "P1372": _("Early Ignition Coil Activation Fault Coil 2"),
    "P1373": _("Early Ignition Coil Activation Fault Coil 3"),
    "P1374": _("Early Ignition Coil Activation Fault Coil 4"),
    "P1440": _("Evap System Purge Valve Stuck Open Fault"),
    "P1441": _("Evap System Purge Valve Flow 1 Fault"),
    "P1442": _("Evap System Purge Valve Blocked Fault"),
    "P1447": _("Evap System Purge Valve Open or Short Circuit Fault"),
    "P1448": _("Evap System Purge Valve Flow 2 Fault"),
    "P1508": _("Idle Speed Control Open Circuit Fault"),
    "P15O9": _("Idle Speed Control Short Circuit Fault"),
    "P1514": _("Neutral Drive Load Fault"),
    "P1516": _("Neutral Drive Gear Change Fault"),
    "P1517": _("Neutral Drive Cranking Fault"),
    "P1607": _("Malfunction Indicator Lamp Short Circuit Fault"),
    "P1608": _("Malfunction Indicator Lamp Open Circuit Fault"),
    "P1620": _("Reprogramming Code Learn Fault"),
    "P1621": _("Serial Data Link Dead Fault"),
    "P1622": _("Repeated Wrong ECM Security Code Fault"),
    "P1623": _("ECM Security Code Fault"),
    "P1701": _("Transfer Box Line Fault"),
    "P1703": _("Transfer Box Line Open Circuit Fault"),
    "P1708": _("Transfer Box Line Short Circuit Fault"),
    "P1775": _("Gearbox Fault"),
    "P1776": _("Gearbox Ignition Retard Request Timeout Fault"),
    "P1777": _("Gearbox Ignition Retard Request Line Fault"),
}
