#!/usr/bin/python
# -*- coding: iso-8859-15 -*-
#
# volkswagen_codes.py
#
# Copyright (C) Ben Van Mechelen 2008-2009 <me@benvm.be>
# 
# This file is part of Garmon 
# 
# Garmon is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, write to:
#   The Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor
#   Boston, MA  02110-1301, USA.


from gettext import gettext as _

DTC_CODES_MANUFACTURER = {
    "P1102": _("O2S Heating Circuit Bank 1 Sensor 1 Voltage Too Low/Air Leak"),
    "P1105": _("O2S Heating Circuit Bank 1 Sensor 2 Short To Positive"),
    "P1107": _("O2S Heating Circuit Bank 2 Sensor 1 Short To Positive"),
    "P1110": _("O2S Heating Circuit Bank 2 Sensor 2 Short To Positive"),
    "P1113": _("O2S Sensor Heater Resistance Too High Bank 1 Sensor 1"),
    "P1115": _("O2S Sensor Heater Circuit Short To Ground Bank 1 Sensor 1"),
    "P1116": _("O2S Sensor Heater Circuit Open Bank 1 Sensor 1"),
    "P1117": _("O2S Sensor Heater Circuit Short To Ground Bank 1 Sensor 2"),
    "P1118": _("O2S Sensor Heater Circuit Open Bank 1 Sensor 2"),
    "P1127": _("Long Term Fuel Trim B1 System Too Rich"),
    "P1128": _("Long Term Fuel Trim B1 System Too Lean"),
    "P1129": _("Long Term Fuel Trim B2 System Too Rich"),
    "P1130": _("Long Term Fuel Trim B2 System Too Lean"),
    "P1136": _("Long Term Fuel Trim Add. Fuel B1 System Too Lean"),
    "P1137": _("Long Term Fuel Trim Add. Fuel B1 System Too Rich"),
    "P1138": _("Long Term Fuel Trim Add. Fuel B2 System Too Lean"),
    "P1139": _("Long Term Fuel Trim Add. Fuel B2 System Too Rich"),
    "P1141": _("Load Calculation Cross Check Range/Performance"),
    "P1144": _("Mass Air Flow Sensor Open/Short To Ground."),
    "P1145": _("Mass Air Flow Sensor Short To Positive."),
    "P1146": _("Mass Air Flow Sensor Supply Voltage."),
    "P1155": _("Manifold Absolute Pressure Sensor Short To Positive."),
    "P1156": _("Manifold Absolute Pressure Sensor Open/Short To Ground."),
    "P1157": _("Manifold Absolute Pressure Sensor Supply Voltage."),
    "P1160": _("Intake Air Temperature Sensor Short To Ground."),
    "P1161": _("Intake Air Temperature Sensor Open/Short To Positive."),
    "P1162": _("Intake Air Temperature Sensor Short To Ground."),
    "P1163": _("Fuel Temperature Sensor Open/Short To Positive."),
    "P1164": _("Fuel Temperature Sensor Implausible Signal."),
    "P1171": _("Throttle Actuation Potentiometer Sign. 2 Range/Performance"),
    "P1172": _("Throttle Actuation Potentiometer Sign. 2 Signal Too Low"),
    "P1173": _("Throttle Actuation Potentiometer Sign. 2 Signal Too High"),
    "P1176": _("Rear O2S Correction"),
    "P1177": _("O2 Correction Behind Catalyst B1 Limit Attained"),
    "P1196": _("O2S Heater Circuit Bank 1 Sensor 1 Electrical Malfunction"),
    "P1197": _("O2S Heater Circuit Bank 2 Sensor 1 Electrical Malfunction"),
    "P1198": _("O2S Heater Circuit Bank 1 Sensor 2 Electrical Malfunction"),
    "P1199": _("O2S Heater Circuit Bank 2 Sensor 2 Electrical Malfunction"),
    "P1213": _("Injector Circuit Cylinder 1 Short To Positive"),
    "P1214": _("Injector Circuit Cylinder 2 Short To Positive"),
    "P1215": _("Injector Circuit Cylinder 3 Short To Positive"),
    "P1216": _("Injector Circuit Cylinder 4 Short To Positive"),
    "P1217": _("Injector Circuit Cylinder 5 Short To Positive"),
    "P1218": _("Injector Circuit Cylinder 6 Short To Positive"),
    "P1225": _("Injector Circuit Cylinder 1 Short To Ground"),
    "P1226": _("Injector Circuit Cylinder 2 Short To Ground"),
    "P1227": _("Injector Circuit Cylinder 3 Short To Ground"),
    "P1228": _("Injector Circuit Cylinder 4 Short To Ground"),
    "P1229": _("Injector Circuit Cylinder 5 Short To Ground"),
    "P1230": _("Injector Circuit Cylinder 6 Short To Ground"),
    "P1237": _("Injector Circuit Open Cylinder 1"),
    "P1238": _("Injector Circuit Open Cylinder 2"),
    "P1239": _("Injector Circuit Open Cylinder 3"),
    "P1240": _("Injector Circuit Open Cylinder 4"),
    "P1241": _("Injector Circuit Open Cylinder 5"),
    "P1242": _("Injector Circuit Open Cylinder 6"),
    "P1245": _("Needle Lift Sensor Short To Ground"),
    "P1246": _("Needle Lift Implausible Signal"),
    "P1247": _("Needle Lift Sensor Open/Short To Positive"),
    "P1248": _("Start Of Cold Start Injector Control Difference"),
    "P1251": _("Start Of Cold Start Injector Short To Positive"),
    "P1252": _("Start Of Cold Start Injector Open/Short To Ground"),
    "P1255": _("Engine Coolant Temperature Sensor Short To Ground"),
    "P1256": _("Engine Coolant Temperature Sensor Open/Short To Positive"),
    "P1300": _("Misfire Detected, Fuel Level Too Low"),
    "P1250": _("Fuel Level Too Low"),
    "P1325": _("Cyl. 1 Knock Control Limit Attained"),
    "P1326": _("Cyl. 2 Knock Control Limit Attained"),
    "P1327": _("Cyl. 3 Knock Control Limit Attained"),
    "P1328": _("Cyl. 4 Knock Control Limit Attained"),
    "P1329": _("Cyl. 5 Knock Control Limit Attained"),
    "P1330": _("Cyl. 6 Knock Control Limit Attained"),
    "P1336": _("Engine Torque Adaption At Limit"),
    "P1337": _("CMP Sensor Bank 1 Short To Ground"),
    "P1338": _("CMP Sensor Bank 1 Open Circuit Or Short To Positive"),
    "P1340": _("CKP/CMP Sensor Signals Out Of Sequence"),
    "P1341": _("Ignition Coil Output Stage 1 Short To Ground"),
    "P1343": _("Ignition Coil Output Stage 2 Short To Ground"),
    "P1345": _("Ignition Coil Output Stage 3 Short To Ground"),
    "P1354": _("Modulating Piston Displacement Sensor Electrial Circuit Malfunction"),
    "P1386": _("Internal Control Module Knock Control Error"),
    "P1387": _("Control Unit Internal Altitude Sensor"),
    "P1391": _("CMP Sensor Bank 2 Short To Ground"),
    "P1392": _("CMP Sensor Bank 2 Open Circuit/Short To Positive"),
    "P1393": _("Ignition Coil Power Output Stage 1 Malfunction"),
    "P1394": _("Ignition Coil Power Output Stage 2 Malfunction"),
    "P1395": _("Ignition Coil Power Output Stage 3 Malfunction"),
    "P1401": _("EGR Valve Power Stage Short To Ground"),
    "P1402": _("EGR Vacuum Regulator Solenoid Valve Short To Positive"),
    "P1403": _("EGR System Control Difference"),
    "P1407": _("EGR Temperature Sensor Signal Too Low"),
    "P1408": _("EGR Temperature Sensor Signal Too High"),
    "P1410": _("Tank Ventilation Valve Circuit Short To B+"),
    "P1420": _("Secondary Air Injection Control Module Electrical Malfunction"),
    "P1421": _("Secondary Air Injection Valve Circuit Short To Ground"),
    "P1422": _("Secondary Air Injection Valve Circuit Short To B+"),
    "P1424": _("Secondary Air Injection System Bank 1 Leak Detected"),
    "P1425": _("Tank Ventilation Valve Short To Ground"),
    "P1426": _("Tank Ventilation Valve Open Circuit"),
    "P1432": _("Secondary Air Injection Valve Open"),
    "P1433": _("Secondary Air Injection Pump Relay Circuit Open"),
    "P1434": _("Secondary Air Injection Pump Relay Circuit Short To Positive"),
    "P1435": _("Secondary Air Injection Pump Relay Circuit Short To Ground"),
    "P1436": _("Secondary Air Injection Pump Relay Circuit Electrical Malfunction"),
    "P1440": _("EGR Valve Power Stage Open"),
    "P1441": _("EGR Vacuum Regulator Solenoid Valve Open/Short To Ground"),
    "P1450": _("Secondary Air Injection System Circuit Short To Positive"),
    "P1451": _("Secondary Air Injection Circuit Short To Ground"),
    "P1452": _("Secondary Air Injection System Circuit Open"),
    "P1471": _("EVAP Control System LDP Circuit Short to Positive"),
    "P1472": _("EVAP Control System LDP Circuit Short To Ground"),
    "P1473": _("EVAP Control System LDP Open Circuit"),
    "P1475": _("EVAP Control System LDP Malfunction/Signal Circuit Open"),
    "P1476": _("EVAP Control System LDP Malfunction/Insufficient Vacuum"),
    "P1477": _("EVAP Control System LDP Malfunction"),
    "P1478": _("EVAP Control System LDP Clamped Tube Detected"),
    "P1500": _("Fuel Pump Relay Electrical Circuit Malfunction"),
    "P1501": _("Fuel Pump Relay Circuit Short To Ground"),
    "P1502": _("Fuel Pump Relay Circuit Short To Positive"),
    "P1505": _("Closed Throttle Position Does Not Close/Open Circuit"),
    "P1506": _("Closed Throttle Position Switch Does Not Open./Short To Ground"),
    "P1512": _("Intake Manifold Changeover Valve Circuit Short To Positive"),
    "P1515": _("Intake Manifold Changeover Valve Circuit Short To Ground"),
    "P1516": _("Intake Manifold Changeover Valve Circuit Open"),
    "P1519": _("Intake Camshaft Control Bank 1 Malfunction"),
    "P1522": _("Intake Camshaft Control Bank 2 Malfunction"),
    "P1537": _("Fuel Cut-off Valve Incorrect Function"),
    "P1538": _("Fuel Cut-off Valve Open/Short To Ground"),
    "P1539": _("Clutch Pedal Switch Signal Fault"),
    "P1540": _("VSS Signal Too High"),
    "P1541": _("Fuel Pump Relay Circuit Open"),
    "P1542": _("Throttle Actuation Potentiometer Range/Performance"),
    "P1543": _("Throttle Actuation Potentiometer Signal Too Low"),
    "P1544": _("Throttle Actuation Potentiometer Signal Too High"),
    "P1545": _("Throttle Position Control Malfunction"),
    "P1546": _("Wastegate Bypass Regulator Valve Short To Positive"),
    "P1547": _("Wastegate Bypass Regulator Valve Short To Ground"),
    "P1548": _("Wastegate Bypass Regulator Valve Open"),
    "P1549": _("Wastegate Bypass Regulator Valve Open/Short To Ground"),
    "P1550": _("Charge Pressure Control Difference"),
    "P1555": _("Charge Pressure Upper Limit Exceeded"),
    "P1556": _("Charge Pressure Negative Deviation"),
    "P1557": _("Charge Pressure Positive Deviation"),
    "P1558": _("Throttle Actuator Electrical Malfunction"),
    "P1559": _("Idle Speed Control Throttle Position Adaption Malfunction"),
    "P1560": _("Maximum Engine Speed Exceeded"),
    "P1561": _("Quantity Adjuster Control Difference"),
    "P1562": _("Quantity Adjuster Upper Stop Value"),
    "P1563": _("Quantity Adjuster Lower Stop Value"),
    "P1564": _("Idle Speed Control Throttle Position Low Voltage During Adaption"),
    "P1565": _("Idle Speed Control Throttle Position Lower Limit Not Obtained"),
    "P1568": _("Idle Speed Control Throttle Position Mechanical Malfunction"),
    "P1569": _("Switch For CCS Signal Faulty"),
    "P1580": _("Throttle Actuator B1 Malfunction"),
    "P1582": _("Idle Adaptation At Limit"),
    "P1600": _("Power Supply Terminal No. 15 Low Voltage"),
    "P1602": _("Power Supply Terminal No. 30 Low Voltage"),
    "P1603": _("Internal Control Module Self Check"),
    "P1606": _("Rough Road Spec. Engine Torque ABS-ECU Electrical Malfunction"),
    "P1611": _("MIL Call-Up Circuit/TCM Short To Ground"),
    "P1612": _("Engine Control Module Incorrect Coding"),
    "P1613": _("MIL Call-Up Circuit Open/Short To Positive"),
    "P1616": _("Glow Plug Indicator Lamp Short To Positive"),
    "P1617": _("Glow Plug Indicator Lamp Open/Short To Ground"),
    "P1618": _("Glow Plug Relay Short To Positive"),
    "P1619": _("Glow Plug Relay Open/Short To Ground"),
    "P1624": _("MIL Request Signal Active"),
    "P1626": _("Data Bus Drive Missing Command From M/T"),
    "P1630": _("Accelerator Pedal Position Sensor 1 Signal Too Low"),
    "P1631": _("Accelerator Pedal Position Sensor 1 Signal Too High"),
    "P1632": _("Accelerator Pedal Position Sensor 1/2 Supply Voltage"),
    "P1633": _("Accelerator Pedal Position Sensor 2 Signal Too Low"),
    "P1634": _("Accelerator Pedal Position Sensor 2 Signal Too High"),
    "P1639": _("Accelerator Pedal Position Sensor 1/2 Range Performance"),
    "P1640": _("Internal Control Module (EEPROM) Error"),
    "P1648": _("CAN-Bus System Component Failure"),
    "P1649": _("Data Bus Powertrain Missing Message From Brake Controller"),
    "P1676": _("Drive By Wire MIL Circuit Electrical Malfunction"),
    "P1677": _("Drive By Wire MIL Circuit Short To Positive"),
    "P1678": _("Drive By Wire MIL Circuit Short To Ground"),
    "P1679": _("Drive By Wire MIL Circuit Open Circuit"),
    "P1681": _("Control Module Programming Not Finished"),
    "P1686": _("Control Unit Error, Programming Error"),
    "P1690": _("MIL Malfunction"),
    "P1691": _("MIL Open Circuit"),
    "P1692": _("MIL Short To Ground"),
    "P1693": _("MIL Short To Positive"),
    "P1778": _("Solenoid EV7 Electrical Malfunction"),
    "P1780": _("Engine Intervention Readable"),
    "P1851": _("Data Bus Drive Missing Command From ABS"),
    "P1854": _("Drive Train CAN-Bus Inoperative"),
}
